import type { Topic } from "@/lib/topics";

export const ENGLISH_TOPICS: Topic[] = [
  {
    id: "school-holidays",
    themeId: "english-term-i",
    themeName: "Term I",
    title: "School holidays",
    estMinutes: 16,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Holiday topics help learners practise speaking, reading and writing about plans, activities and experiences using correct tenses and clear vocabulary.",
      learningObjectives: [
        "Talk and write about holiday plans and holiday activities.",
        "Use future tense for plans and past tense for completed activities.",
        "Read short passages about holidays and answer questions.",
        "Write a short composition or paragraph about a holiday experience.",
      ],
      whatYouNeedToKnow: [
        "Holiday plans are things someone intends to do during the holiday. Use future expressions such as will, shall, going to, intend to, plan to and hope to.",
        "Holiday activities are things people do or did during holidays, such as visiting relatives, helping at home, reading, farming, travelling, playing games, attending church or mosque, and revising school work.",
        "When writing about plans, use future tense: I will visit my grandmother. When writing about completed activities, use past tense: I visited my grandmother.",
        "A good holiday paragraph has a clear topic sentence, supporting details and a closing sentence. Use time words such as first, then, later, afterwards and finally.",
        "In comprehension, read the questions first, then read the passage carefully, underline key words and answer in complete sentences where needed.",
      ],
      worked: {
        problem: "Change this sentence to future tense: 'I visited my aunt during the holiday.'",
        steps: [
          "Step 1. Identify the verb in past tense: visited.",
          "Step 2. Replace it with a future form: will visit.",
          "Step 3. Keep the rest of the sentence clear.",
        ],
        answer: "Answer: I will visit my aunt during the holiday.",
      },
      commonMistakes: [
        "Mixing past tense and future tense in the same sentence.",
        "Writing a list of activities without connecting words.",
        "Starting every sentence with 'I' when writing a composition.",
        "Giving one-word answers to comprehension questions that need full sentences.",
      ],
      tryThis: {
        question: "Which sentence talks about a holiday plan?",
        choices: ["I will read two storybooks.", "I read two storybooks last week.", "I am reading now.", "I had read before supper."],
        correct: 0,
        explanation: "'I will read two storybooks' uses future tense, so it is a plan.",
      },
      writingTasks: [
        {
          title: "Composition: My useful holiday",
          prompt: "Write a short composition about a holiday that was useful to you and your family.",
          planningSteps: [
            "Choose whether you are writing about a past holiday or a future holiday plan.",
            "List three main activities, such as helping at home, visiting relatives, reading or farming.",
            "Arrange the activities in time order using first, then, afterwards and finally.",
            "End by saying what you learnt or why the holiday was useful.",
          ],
          checklist: [
            "Correct tense is used consistently.",
            "The composition has a beginning, middle and ending.",
            "Sequence words connect the events.",
            "Sentences start with capital letters and end with full stops.",
          ],
          modelOpening: "During my last holiday, I stayed with my parents in the village. It was a useful holiday because I learnt new skills and helped my family.",
        },
      ],
      recap: [
        "Use future tense for holiday plans.",
        "Use past tense for completed holiday activities.",
        "Good writing uses details and connecting words.",
        "Comprehension answers should match the passage.",
      ],
    },
    quiz: [
      { q: "Which phrase shows a future holiday plan?", choices: ["I am going to visit my uncle", "I visited my uncle", "I was visiting my uncle", "I had visited my uncle"], correct: 0, why: "'Am going to' shows a future plan." },
      { q: "Choose the correct past tense: We ___ football during the holiday.", choices: ["played", "play", "will play", "playing"], correct: 0, why: "'Played' is the correct past tense form." },
      { q: "Which word can connect events in a paragraph?", choices: ["Afterwards", "Table", "Blue", "Quickly only"], correct: 0, why: "'Afterwards' connects events in time order." },
      { q: "A topic sentence usually tells:", choices: ["The main idea of a paragraph", "Only the writer's age", "The page number", "The punctuation mark only"], correct: 0, why: "A topic sentence introduces the main idea." },
      { q: "Which is a holiday activity?", choices: ["Helping parents at home", "Sitting an end-of-term exam now", "Marking registers only", "Drawing a timetable only"], correct: 0, why: "Helping at home is a common holiday activity." },
      { q: "Which sentence is correct?", choices: ["I will visit my grandmother.", "I will visited my grandmother.", "I visiting my grandmother.", "I visit yesterday."], correct: 0, why: "'Will visit' is the correct future form." },
      { q: "When answering comprehension questions, first:", choices: ["Read carefully", "Guess quickly", "Ignore the passage", "Copy any sentence"], correct: 0, why: "Careful reading helps you find the correct answer." },
    ],
  },
  {
    id: "letter-writing",
    themeId: "english-term-i",
    themeName: "Term I",
    title: "Letter writing",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Letters are common in English exams and real life. Learners need to know the difference between informal and formal letters and use the correct format.",
      learningObjectives: [
        "Identify parts of informal and formal letters.",
        "Write informal letters to friends and relatives.",
        "Write formal letters for official purposes.",
        "Use suitable tone, punctuation and paragraphing in letters.",
      ],
      whatYouNeedToKnow: [
        "An informal letter is written to someone you know well, such as a friend, parent, brother, sister or relative. The tone is friendly and personal, but the writing should still be neat, clear and correctly punctuated.",
        "A formal letter is written for official purposes, such as to a head teacher, chairperson, manager, editor or organisation. The tone is polite, respectful, direct and not slangy.",
        "An informal letter usually has the writer's address, date, greeting, body, closing and name. Examples of greetings include Dear Aunt Sarah or Dear John. It may ask about the receiver, share news and end warmly.",
        "A formal letter usually has the writer's address, date, receiver's address, greeting, heading or subject, body, complimentary close, signature and name. If the greeting is Dear Sir or Dear Madam, the close is usually Yours faithfully.",
        "A strong formal-letter body uses three clear paragraphs: why you are writing, the important details or reasons, and the polite request or closing statement.",
        "A strong informal-letter body is conversational but organised: greeting/well-wishes, main news or purpose, extra details, and a friendly closing.",
        "In PLE-style tasks, first identify the receiver and purpose. Then choose the correct format, tone and vocabulary. Do not write a friendly letter when the task asks for an official request, complaint, application or permission letter.",
      ],
      worked: {
        problem: "Which type of letter should a pupil write to the head teacher asking for permission to be absent, and what should the heading be?",
        steps: [
          "Step 1. Identify the receiver: the head teacher is an official person.",
          "Step 2. Identify the purpose: asking for permission is official.",
          "Step 3. Choose a formal letter with a short heading that states the purpose.",
          "Step 4. Use polite language and give the reason, date of absence and promise to catch up with missed work.",
        ],
        answer: "Answer: The pupil should write a formal letter. A suitable heading is: REQUEST FOR PERMISSION TO BE ABSENT FROM SCHOOL.",
      },
      commonMistakes: [
        "Using informal slang in formal letters.",
        "Forgetting the receiver's address or heading in a formal letter.",
        "Writing one long paragraph instead of clear paragraphs.",
        "Not matching the letter type to the question.",
        "Writing Yours sincerely/Yours faithfully carelessly without checking the greeting.",
        "Leaving out important task details such as date, reason, request or receiver.",
      ],
      tryThis: {
        question: "Which item is usually found in a formal letter but not always in an informal letter?",
        choices: ["Receiver's address", "Writer's address", "Date", "Greeting"],
        correct: 0,
        explanation: "Formal letters normally include the receiver's address.",
      },
      writingTasks: [
        {
          title: "Formal letter: Request for permission",
          prompt: "Write a formal letter to your head teacher requesting permission to be absent from school for one day.",
          planningSteps: [
            "Write the writer's address and date at the top.",
            "Write the receiver's address below the date.",
            "Use a polite greeting and a clear heading.",
            "Explain the reason, the date of absence and how you will catch up with missed work.",
            "Close politely with Yours faithfully, signature and name.",
          ],
          checklist: [
            "Writer's address, date and receiver's address are present.",
            "The heading states the purpose clearly.",
            "Tone is formal, polite and respectful.",
            "Paragraphs are organised and the request is clear.",
            "The complimentary close matches a formal letter.",
          ],
          modelOpening: "RE: REQUEST FOR PERMISSION TO BE ABSENT FROM SCHOOL. I humbly request permission to be absent from school on Friday because I have a medical appointment.",
        },
        {
          title: "Informal letter: Holiday news",
          prompt: "Write a friendly letter to your cousin telling him or her about what you did during the holiday.",
          planningSteps: [
            "Begin with your address, date and a friendly greeting.",
            "Ask about your cousin before giving your news.",
            "Describe two or three holiday activities with clear details.",
            "End warmly and write your name.",
          ],
          checklist: [
            "The tone is friendly but still correct.",
            "Past tense is used for completed holiday activities.",
            "The body is divided into clear paragraphs.",
            "The closing is suitable for a relative or friend.",
          ],
          modelOpening: "Dear Sarah, I hope you are well. I am writing to tell you about the interesting activities I did during the holiday.",
        },
      ],
      recap: [
        "Informal letters are friendly and personal.",
        "Formal letters are official and polite.",
        "Format matters in letter writing.",
        "A heading helps a formal letter show its purpose quickly.",
        "The body should answer the task clearly in organised paragraphs.",
      ],
    },
    quiz: [
      { q: "A letter to a head teacher is usually:", choices: ["Formal", "Informal", "A poem", "A dialogue only"], correct: 0, why: "A head teacher is an official receiver, so the letter is formal." },
      { q: "Which greeting is suitable for an informal letter?", choices: ["Dear Uncle Ben", "Dear Sir/Madam", "To the Manager", "Subject: Complaint"], correct: 0, why: "'Dear Uncle Ben' is friendly and personal." },
      { q: "A formal letter should use language that is:", choices: ["Polite and respectful", "Abusive", "Slang-filled", "Careless"], correct: 0, why: "Formal letters require polite and respectful language." },
      { q: "Which part states the purpose of a formal letter briefly?", choices: ["Heading or subject", "Stamp colour", "Story title", "Postscript only"], correct: 0, why: "The heading or subject tells the purpose of the formal letter." },
      { q: "Which is a complimentary close for a formal letter?", choices: ["Yours faithfully", "Bye my guy", "See you soon", "Cheers only"], correct: 0, why: "'Yours faithfully' is a formal complimentary close." },
      { q: "An informal letter is commonly written to:", choices: ["A friend", "A district office only", "A company manager only", "A police station only"], correct: 0, why: "Informal letters are written to people we know well." },
      { q: "Why are paragraphs important in letters?", choices: ["They organise ideas clearly", "They hide the message", "They replace punctuation", "They make spelling unnecessary"], correct: 0, why: "Paragraphs help organise ideas and make the letter easy to read." },
    ],
  },
  {
    id: "examinations",
    themeId: "english-term-i",
    themeName: "Term I",
    title: "Examinations",
    estMinutes: 17,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: P7 learners prepare for PLE. They need language for preparing for examinations, sitting examinations and talking about exam rules, revision and confidence.",
      learningObjectives: [
        "Use vocabulary related to examinations and revision.",
        "Describe ways of preparing for examinations.",
        "Explain good behaviour when sitting examinations.",
        "Answer comprehension and grammar questions about examinations.",
      ],
      whatYouNeedToKnow: [
        "Examination vocabulary includes revise, timetable, candidate, invigilator, instructions, answer sheet, question paper, results, pass, fail, prepare and confidence.",
        "Preparing for examinations includes reading notes, making a revision timetable, practising past questions, asking for help, sleeping enough, eating well and arriving early.",
        "When sitting examinations, learners should read instructions carefully, write their names or index numbers correctly, manage time well, answer the required number of questions and avoid cheating.",
        "Good examination writing is clear, organised and relevant. In English, read comprehension passages carefully, check grammar choices, plan compositions and revise punctuation.",
        "Confidence matters. A learner should stay calm, pray if they wish, breathe, read carefully and attempt questions they understand first.",
      ],
      worked: {
        problem: "Rewrite politely: 'Give me my results now!'",
        steps: [
          "Step 1. Identify the problem: the sentence sounds rude.",
          "Step 2. Use polite words such as please and may.",
          "Step 3. Keep the meaning.",
        ],
        answer: "Answer: May I please have my results now?",
      },
      commonMistakes: [
        "Starting to answer before reading instructions.",
        "Spending too much time on one question.",
        "Using informal language where polite language is needed.",
        "Failing to plan a composition before writing.",
      ],
      tryThis: {
        question: "Who supervises learners during an examination?",
        choices: ["Invigilator", "Candidate", "Postman", "Passenger"],
        correct: 0,
        explanation: "An invigilator supervises candidates during an examination.",
      },
      writingTasks: [
        {
          title: "Paragraph: How to prepare for examinations",
          prompt: "Write one well-organised paragraph explaining how a P7 learner should prepare for examinations.",
          planningSteps: [
            "Start with a topic sentence about good preparation.",
            "Give at least three preparation habits.",
            "Use linking words such as firstly, secondly, also and finally.",
            "End with a sentence about confidence or success.",
          ],
          checklist: [
            "The paragraph has one clear main idea.",
            "Examples are practical for a P7 learner.",
            "Linking words are used correctly.",
            "The writing encourages honest examination behaviour.",
          ],
          modelOpening: "A P7 learner should prepare for examinations early and carefully. Firstly, the learner should make a revision timetable and follow it.",
        },
      ],
      recap: [
        "Revision should be planned.",
        "Read instructions before answering.",
        "Manage time during examinations.",
        "Use polite and clear examination language.",
      ],
    },
    quiz: [
      { q: "A person who sits an examination is called a:", choices: ["Candidate", "Invigilator", "Pilot", "Editor"], correct: 0, why: "A candidate is a person sitting an examination." },
      { q: "What should you read first in an exam?", choices: ["Instructions", "The wall", "Another pupil's paper", "Only the last question"], correct: 0, why: "Instructions tell you what to do." },
      { q: "Which habit helps exam preparation?", choices: ["Making a revision timetable", "Cheating", "Sleeping in class", "Ignoring weak topics"], correct: 0, why: "A revision timetable helps organise study time." },
      { q: "An invigilator is a person who:", choices: ["Supervises an examination", "Sits the exam as a pupil", "Prints newspapers only", "Marks roads"], correct: 0, why: "Invigilators supervise examinations." },
      { q: "Which is wrong during an exam?", choices: ["Cheating", "Reading instructions", "Managing time", "Writing clearly"], correct: 0, why: "Cheating is dishonest and not allowed." },
      { q: "Choose the polite request:", choices: ["May I borrow your ruler, please?", "Give me ruler!", "You must give me now", "Ruler here!"], correct: 0, why: "'May I...' and 'please' make the request polite." },
      { q: "Why should a learner plan a composition?", choices: ["To organise ideas before writing", "To waste time", "To avoid punctuation", "To copy the question only"], correct: 0, why: "Planning helps organise ideas and avoid confusion." },
    ],
  },
  {
    id: "electronic-media",
    themeId: "english-term-ii",
    themeName: "Term II",
    title: "Electronic media",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Learners receive information from radio, television, phones and other electronic media. They need vocabulary, comprehension and safe communication habits.",
      learningObjectives: [
        "Name types of electronic media.",
        "Explain uses and dangers of electronic media.",
        "Listen to or read media messages critically.",
        "Use suitable language for announcements, news and messages.",
      ],
      whatYouNeedToKnow: [
        "Electronic media are means of communication that use electronic technology. Examples include radio, television, mobile phones, computers, internet, email and public address systems.",
        "Radio and television provide news, education, entertainment, weather information, announcements, advertisements and emergency messages.",
        "Other electronic media such as phones and computers help people send messages, learn online, record information and communicate quickly.",
        "Electronic media can also cause problems such as misinformation, addiction, time wasting, exposure to harmful content and unsafe communication with strangers.",
        "Good media users listen carefully, check facts, use polite language, protect private information and ask trusted adults for guidance.",
      ],
      worked: {
        problem: "A radio announcement says: 'The meeting has been postponed.' What does postponed mean?",
        steps: [
          "Step 1. Use context: the meeting will not happen at the planned time.",
          "Step 2. Think of a simpler word: delayed.",
          "Step 3. Answer clearly.",
        ],
        answer: "Answer: Postponed means delayed to a later time or date.",
      },
      commonMistakes: [
        "Believing every message heard on media without checking.",
        "Sharing private information online or by phone.",
        "Confusing electronic media with print media.",
        "Using rude language in messages and comments.",
      ],
      tryThis: {
        question: "Which is an example of electronic media?",
        choices: ["Radio", "Newspaper only", "Stone tablet", "Handwritten note only"],
        correct: 0,
        explanation: "Radio uses electronic technology to communicate messages.",
      },
      writingTasks: [
        {
          title: "Announcement: School radio message",
          prompt: "Write a short radio announcement informing pupils about a school clean-up activity.",
          planningSteps: [
            "State the event clearly in the first sentence.",
            "Give the date, time and place.",
            "Mention what pupils should bring or do.",
            "End with a polite call to action.",
          ],
          checklist: [
            "The announcement is short and clear.",
            "Date, time and place are included.",
            "Language is polite and suitable for public media.",
            "The message does not include rumours or private information.",
          ],
          modelOpening: "This is to inform all P7 pupils that there will be a school clean-up activity on Friday at 8:00 a.m. near the main compound.",
        },
      ],
      recap: [
        "Electronic media use electronic technology.",
        "Radio, TV and phones can inform and educate.",
        "Media messages should be checked carefully.",
        "Private information should be protected.",
      ],
    },
    quiz: [
      { q: "Which is electronic media?", choices: ["Television", "Newspaper", "Magazine", "Poster only"], correct: 0, why: "Television uses electronic technology." },
      { q: "Which is a use of radio?", choices: ["Broadcasting news", "Cooking food directly", "Carrying water", "Digging soil"], correct: 0, why: "Radio broadcasts news, education and entertainment." },
      { q: "False information spread through media is called:", choices: ["Misinformation", "Punctuation", "Paragraphing", "Synonym"], correct: 0, why: "Misinformation means false or inaccurate information." },
      { q: "Which habit is safe when using a phone?", choices: ["Protecting private information", "Sharing passwords", "Chatting with strangers secretly", "Sending insults"], correct: 0, why: "Private information should be protected." },
      { q: "An announcement is mainly used to:", choices: ["Give information to people", "Hide information", "End communication", "Replace all lessons"], correct: 0, why: "Announcements inform people about something important." },
      { q: "Which is not electronic media?", choices: ["Printed newspaper", "Radio", "Television", "Mobile phone"], correct: 0, why: "A printed newspaper is print media, not electronic media." },
      { q: "What should you do before believing a surprising media message?", choices: ["Check from reliable sources", "Forward it immediately", "Ignore adults", "Add false details"], correct: 0, why: "Checking reliable sources helps avoid spreading false information." },
    ],
  },
  {
    id: "rights-responsibilities-freedom",
    themeId: "english-term-ii",
    themeName: "Term II",
    title: "Rights, responsibilities and freedom",
    estMinutes: 20,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Learners need language for discussing children's rights, freedoms, responsibilities and animal needs respectfully and clearly.",
      learningObjectives: [
        "Explain children's rights and responsibilities using clear English.",
        "Use vocabulary related to freedom, care and protection.",
        "Discuss animal needs and humane treatment.",
        "Write sentences or paragraphs about rights and responsibilities.",
      ],
      whatYouNeedToKnow: [
        "A right is something a person is entitled to, such as education, health care, food, shelter, protection, play and expression. A freedom is the ability to do something without unfair restriction, while respecting other people's rights.",
        "A responsibility is a duty. Children have responsibilities such as respecting others, helping at home, caring for school property, obeying reasonable rules, keeping clean and working hard at school.",
        "Rights and responsibilities go together. For example, a child has a right to education and a responsibility to attend school, listen, revise and avoid disturbing others.",
        "Freedom does not mean doing anything one wants. Good freedom is guided by rules, safety, respect and self-control.",
        "Animals also have needs such as food, water, shelter, rest, treatment when sick, enough space and freedom from unnecessary cruelty. People should treat animals humanely.",
        "Useful discussion language includes: In my opinion..., I agree because..., I disagree respectfully because..., For example..., Therefore... These phrases help learners debate without insulting others.",
        "For PLE writing, link each right to a matching duty: right to play with duty to play safely, right to health with duty to keep clean, right to expression with duty to speak respectfully.",
      ],
      worked: {
        problem: "Complete the sentence and explain the link: A child has a right to education and a responsibility to ____.",
        steps: [
          "Step 1. Match the responsibility to the right.",
          "Step 2. Education connects with attending school, listening, revising and doing school work.",
          "Step 3. Complete the sentence clearly.",
          "Step 4. Add one explanation to show understanding, not just a list.",
        ],
        answer: "Answer: A child has a right to education and a responsibility to attend school and learn seriously. This responsibility helps the child benefit from the right.",
      },
      commonMistakes: [
        "Thinking freedom means doing anything without limits.",
        "Listing rights without responsibilities.",
        "Using rude language in debates about rights.",
        "Forgetting animal needs and welfare in the topic.",
        "Writing points without examples or explanations.",
        "Confusing human rights with animal needs instead of discussing each clearly.",
      ],
      tryThis: {
        question: "Which is a responsibility of a learner?",
        choices: ["Respecting teachers and classmates", "Destroying desks", "Bullying others", "Dodging school"],
        correct: 0,
        explanation: "Respecting others is a learner's responsibility.",
      },
      writingTasks: [
        {
          title: "Balanced paragraph: Rights and responsibilities",
          prompt: "Write a paragraph explaining why children's rights should go together with responsibilities.",
          planningSteps: [
            "Define a right and a responsibility in simple words.",
            "Choose two children's rights and match each with a duty.",
            "Give examples from school or home.",
            "End by explaining why responsible children help the community.",
          ],
          checklist: [
            "Rights and responsibilities are both explained.",
            "Each right is linked to a matching duty.",
            "Examples are respectful and realistic.",
            "The paragraph does not say freedom means doing anything without limits.",
          ],
          modelOpening: "Children's rights should go together with responsibilities because every right is enjoyed better when people act carefully and respectfully.",
        },
        {
          title: "Short talk: Caring for animals",
          prompt: "Prepare a short talk about the needs and freedoms of animals kept at home or at school.",
          planningSteps: [
            "Name the animals you are talking about.",
            "List their needs, such as food, water, shelter and treatment.",
            "Explain why cruelty is wrong.",
            "End with one action pupils can take to care for animals.",
          ],
          checklist: [
            "Animal needs are clearly named.",
            "The language is humane and respectful.",
            "The talk gives practical actions.",
            "The conclusion is clear.",
          ],
          modelOpening: "Animals kept by people need care and protection. They need food, clean water, shelter, rest and treatment when they fall sick.",
        },
      ],
      recap: [
        "Rights are entitlements.",
        "Responsibilities are duties.",
        "Freedom must respect other people's rights.",
        "Animals need care and protection from cruelty.",
      ],
    },
    quiz: [
      { q: "Which is a child's right?", choices: ["Education", "Bullying", "Stealing", "Destroying property"], correct: 0, why: "Children have a right to education." },
      { q: "A responsibility is:", choices: ["A duty", "A colour", "A radio", "A holiday only"], correct: 0, why: "A responsibility is a duty one should perform." },
      { q: "Which is a learner's responsibility?", choices: ["Doing homework", "Fighting", "Breaking windows", "Insulting teachers"], correct: 0, why: "Doing homework is part of learning responsibly." },
      { q: "Freedom should be used while:", choices: ["Respecting others", "Hurting others", "Breaking all rules", "Ignoring rights"], correct: 0, why: "Freedom should not violate other people's rights." },
      { q: "Which is an animal need?", choices: ["Food and water", "Cruelty", "Starvation", "Beating"], correct: 0, why: "Animals need food, water, shelter and care." },
      { q: "Which sentence is respectful?", choices: ["I disagree with your idea.", "You are useless.", "Shut up!", "Only I matter."], correct: 0, why: "It disagrees without insulting the person." },
      { q: "Rights and responsibilities:", choices: ["Go together", "Are enemies", "Mean the same as punishment", "Remove all duties"], correct: 0, why: "Rights should be enjoyed together with responsibilities." },
    ],
  },
  {
    id: "environmental-protection",
    themeId: "english-term-iii",
    themeName: "Term III",
    title: "Environmental protection",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Learners need English for explaining why the environment matters and how people can protect it through clear messages, stories, talks and writing.",
      learningObjectives: [
        "Explain the importance of environmental protection.",
        "Name ways of protecting the environment.",
        "Use vocabulary related to pollution, conservation and cleanliness.",
        "Write a short message, paragraph or speech about environmental protection.",
      ],
      whatYouNeedToKnow: [
        "The environment includes land, air, water, plants, animals and the surroundings where people live. Environmental protection means caring for these surroundings and using resources responsibly.",
        "Important vocabulary includes pollution, litter, conserve, recycle, reuse, reduce, afforestation, deforestation, wetland, erosion, sanitation, drought, flood and conservation.",
        "The environment is important because it provides food, water, air, medicine, materials, beauty, rainfall support, soil fertility and homes for living things.",
        "Ways of protecting the environment include planting trees, proper waste disposal, avoiding bush burning, protecting wetlands, using latrines, cleaning compounds, reducing pollution, conserving water and reusing materials where safe.",
        "Environmental messages should be clear and persuasive. Use command forms like Plant trees, Keep water sources clean, Do not litter and Protect wetlands.",
        "A good poster or announcement has a short heading, one clear action and a reason. Example: KEEP OUR WELL CLEAN — Do not dump rubbish near the water source because dirty water spreads disease.",
        "A good speech or paragraph follows a problem → effect → solution pattern: name the problem, explain its danger, then suggest practical actions for homes, schools or communities.",
      ],
      worked: {
        problem: "Write one clear environmental protection poster message about rubbish, with a reason.",
        steps: [
          "Step 1. Identify the problem: rubbish or litter.",
          "Step 2. Use a short command or advice.",
          "Step 3. Add a reason so the message is persuasive.",
          "Step 4. Keep the language simple enough for many people to understand.",
        ],
        answer: "Answer: DO NOT LITTER. Put rubbish in a bin or rubbish pit to keep our compound clean and prevent disease.",
      },
      commonMistakes: [
        "Writing vague messages like 'environment is good' without action.",
        "Confusing pollution with protection.",
        "Forgetting punctuation in posters and messages.",
        "Giving only problems without solutions.",
        "Using long unclear slogans that pupils and community members cannot act on.",
        "Forgetting to mention effects such as disease, erosion, floods or loss of soil fertility.",
      ],
      tryThis: {
        question: "Which sentence is an environmental protection message?",
        choices: ["Do not dump rubbish in water sources.", "Throw all rubbish in the river.", "Cut every tree.", "Burn plastics near classrooms."],
        correct: 0,
        explanation: "It gives clear advice that protects water sources.",
      },
      writingTasks: [
        {
          title: "Speech: Protecting our environment",
          prompt: "Write a short speech to your classmates about ways of protecting the school environment.",
          planningSteps: [
            "Start by greeting the audience.",
            "Name one environmental problem at school.",
            "Explain two effects of the problem.",
            "Give three practical solutions pupils can follow.",
            "End with a strong call to action.",
          ],
          checklist: [
            "The speech has a greeting and conclusion.",
            "Problem, effects and solutions are included.",
            "Environmental vocabulary is used correctly.",
            "The call to action is clear and possible.",
          ],
          modelOpening: "Good morning teachers and fellow pupils. I am going to talk about how we can protect our school environment and keep it healthy.",
        },
        {
          title: "Poster message: Clean water source",
          prompt: "Design words for a poster warning people not to dump rubbish near a water source.",
          planningSteps: [
            "Write a short heading in capital letters.",
            "Give one clear command.",
            "Add one reason connected to health or cleanliness.",
            "Keep the words short enough for people to read quickly.",
          ],
          checklist: [
            "The poster has a clear heading.",
            "The message gives an action, not just a complaint.",
            "A reason is included.",
            "Punctuation makes the message easy to read.",
          ],
          modelOpening: "KEEP OUR WATER CLEAN! Do not dump rubbish near the well because dirty water spreads disease.",
        },
      ],
      recap: [
        "Environmental protection means caring for surroundings.",
        "Clear messages should suggest action and give a reason.",
        "Tree planting, cleanliness, wetland protection and proper waste disposal protect the environment.",
        "Good writing explains problems, effects and solutions.",
      ],
    },
    quiz: [
      { q: "Environmental protection means:", choices: ["Caring for our surroundings", "Destroying forests", "Polluting water", "Burning rubbish anywhere"], correct: 0, why: "It means caring for land, air, water, plants, animals and surroundings." },
      { q: "Which action protects the environment?", choices: ["Planting trees", "Dumping rubbish in rivers", "Burning wetlands", "Cutting all trees"], correct: 0, why: "Planting trees helps protect the environment." },
      { q: "Which word means making something dirty or harmful?", choices: ["Pollution", "Protection", "Conservation", "Cleanliness"], correct: 0, why: "Pollution means making the environment dirty or harmful." },
      { q: "Which is a clear poster message?", choices: ["Keep our water sources clean!", "Water maybe something", "Dirty good river", "Trees no maybe"], correct: 0, why: "It is clear, correct and action-focused." },
      { q: "Why are trees important?", choices: ["They protect soil and support rainfall", "They cause all diseases", "They stop oxygen", "They destroy shade"], correct: 0, why: "Trees protect soil, provide oxygen and support rainfall cycles." },
      { q: "Which is a solution to littering?", choices: ["Use bins or rubbish pits", "Throw rubbish anywhere", "Hide rubbish in wells", "Scatter plastics"], correct: 0, why: "Proper disposal helps control littering." },
      { q: "Good environmental writing should include:", choices: ["Problems and solutions", "Only insults", "No punctuation", "False information"], correct: 0, why: "It should explain the problem and suggest practical solutions." },
    ],
  },
  {
    id: "ceremonies",
    themeId: "english-term-iii",
    themeName: "Term III",
    title: "Ceremonies",
    estMinutes: 20,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Ceremonies are part of family and community life. Learners practise respectful language for marriage and funeral ceremonies, invitations, speeches, descriptions and condolences.",
      learningObjectives: [
        "Use vocabulary related to marriage and funeral ceremonies.",
        "Describe events in a ceremony in correct order.",
        "Write invitations, short speeches or condolence messages.",
        "Use respectful language when discussing cultural ceremonies.",
      ],
      whatYouNeedToKnow: [
        "A ceremony is a formal or special event performed according to custom, religion or community practice. In this topic, the official focus is marriage and funeral ceremonies.",
        "Marriage vocabulary may include bride, bridegroom, couple, invitation, guests, vows, reception, gifts, relatives, introduction, entourage, best man, maid of honour and celebration.",
        "Funeral vocabulary may include deceased, mourners, burial, condolence, sympathy, wreath, service, grief, comfort and bereaved family. Use respectful and kind language when speaking about death.",
        "An invitation should include the occasion, host, date, time, venue and polite request to attend. It may also include dress code, contact person or RSVP if needed.",
        "A condolence message should express sympathy, mention the loss respectfully and offer comfort. Example: We are sorry for the loss of your father. May God comfort your family during this difficult time.",
        "When describing a ceremony, use sequence words such as first, next, later, afterwards and finally. Mention people, place, activities and the importance of the ceremony.",
        "Respect cultural and religious differences. Do not mock customs. Use phrases such as according to their custom, the family members, the guests were welcomed and the mourners comforted the bereaved family.",
      ],
      worked: {
        problem: "Write one polite condolence sentence to a friend whose grandmother has died, and avoid careless language.",
        steps: [
          "Step 1. Use kind and respectful language.",
          "Step 2. Mention sympathy or comfort.",
          "Step 3. Keep it short and sincere.",
          "Step 4. Avoid jokes, blame or commands such as stop crying.",
        ],
        answer: "Answer: I am very sorry for the loss of your grandmother; may your family be comforted during this difficult time.",
      },
      commonMistakes: [
        "Using jokes or careless words when writing about funerals.",
        "Leaving out date, time, host or venue in an invitation.",
        "Mixing up bride and bridegroom.",
        "Describing events without sequence words.",
        "Writing a condolence message as if it were a celebration message.",
        "Mocking cultural practices instead of describing them respectfully.",
      ],
      tryThis: {
        question: "Which word means people attending a funeral?",
        choices: ["Mourners", "Bridegrooms", "Candidates", "Invigilators"],
        correct: 0,
        explanation: "Mourners are people who attend a funeral or grieve for someone who has died.",
      },
      writingTasks: [
        {
          title: "Invitation: Marriage ceremony",
          prompt: "Write an invitation card inviting a family friend to a marriage ceremony.",
          planningSteps: [
            "Name the host or family inviting the guest.",
            "State the occasion clearly.",
            "Give the date, time and venue.",
            "Use polite invitation language.",
            "End with contact or closing information if needed.",
          ],
          checklist: [
            "Occasion, host, date, time and venue are included.",
            "The tone is polite and celebratory.",
            "Names are spelt carefully.",
            "The invitation is neat and easy to understand.",
          ],
          modelOpening: "Mr and Mrs Kato request the pleasure of your company at the marriage ceremony of their daughter, Amina, on Saturday 15th August at 10:00 a.m.",
        },
        {
          title: "Condolence message: Funeral",
          prompt: "Write a short condolence message to a friend whose parent has died.",
          planningSteps: [
            "Begin by expressing sympathy.",
            "Mention the loss respectfully.",
            "Offer comfort or support.",
            "Keep the message sincere and not too long.",
          ],
          checklist: [
            "The language is kind and respectful.",
            "No jokes, blame or careless words are used.",
            "The message comforts the bereaved family.",
            "The sentence is grammatically clear.",
          ],
          modelOpening: "I am very sorry for the loss of your father. May your family be comforted during this difficult time.",
        },
      ],
      recap: [
        "Ceremonies are special formal events.",
        "Marriage and funeral topics need respectful vocabulary.",
        "Invitations need occasion, host, date, time and venue.",
        "Condolence messages should be kind and comforting.",
        "Descriptions of ceremonies should use sequence words and respect culture.",
      ],
    },
    quiz: [
      { q: "A bridegroom is:", choices: ["The man getting married", "The woman getting married", "A mourner", "An invigilator"], correct: 0, why: "The bridegroom is the man getting married." },
      { q: "People attending a funeral are called:", choices: ["Mourners", "Candidates", "Listeners only", "Tourists only"], correct: 0, why: "Mourners grieve or attend a funeral." },
      { q: "Which detail must be in an invitation?", choices: ["Date and venue", "Only shoe size", "Only weather", "Only exam marks"], correct: 0, why: "An invitation should tell people when and where the event will take place." },
      { q: "Which sentence is suitable for condolence?", choices: ["I am sorry for your loss.", "That is funny.", "You deserved it.", "Stop crying now!"], correct: 0, why: "It is kind and respectful." },
      { q: "Which word can show sequence?", choices: ["Finally", "Table", "Blue", "Because only"], correct: 0, why: "'Finally' shows the order of events." },
      { q: "A ceremony is usually:", choices: ["A special formal event", "A spelling mistake", "A type of river", "A punctuation mark"], correct: 0, why: "A ceremony is a special formal event." },
      { q: "Which language is best when discussing funerals?", choices: ["Respectful language", "Rude jokes", "Insults", "Careless slang"], correct: 0, why: "Funerals require respectful and comforting language." },
    ],
  },
];

export function getEnglishTopic(id: string): Topic | undefined {
  return ENGLISH_TOPICS.find((topic) => topic.id === id);
}
