import type { Topic } from "@/lib/topics";

export const SCIENCE_TOPICS: Topic[] = [
  {
    id: "muscular-skeletal-system",
    themeId: "science-human-body",
    themeName: "Human Body",
    title: "Muscular-skeletal system",
    estMinutes: 16,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: The muscular-skeletal system helps the body stand, move, bend, lift and keep its shape. P7 learners need to name important bones, joints and muscles, and know how to care for them.",
      learningObjectives: [
        "Name important bones and muscles in the human body.",
        "Explain the functions of the skeleton and muscles.",
        "Identify common types of joints.",
        "Describe health habits that keep bones and muscles strong.",
        "Recognise common disorders of bones, muscles and joints and how some can be prevented.",
      ],
      whatYouNeedToKnow: [
        "The skeleton is the framework of bones in the body. It gives the body shape, supports soft parts, protects delicate organs, and works with muscles to make movement possible.",
        "Important bones include the skull, backbone, ribs, humerus, radius, ulna, pelvis, femur, tibia and fibula. The skull protects the brain, the ribs protect the heart and lungs, and the backbone supports the body and protects the spinal cord.",
        "Muscles are body tissues that contract and relax to cause movement. Voluntary muscles are controlled by our will, such as muscles used for walking or writing. Involuntary muscles work without our direct control, such as muscles in the intestines and blood vessels.",
        "A joint is a place where two or more bones meet. Examples include hinge joints at the elbow and knee, ball-and-socket joints at the shoulder and hip, pivot joints in the neck, and gliding joints in the wrist and ankle.",
        "Bones and muscles can be affected by diseases and disorders such as rickets, fractures, sprains, dislocations, arthritis and poor posture. Some are caused by accidents, poor feeding, infection, or careless body use.",
        "Good health habits include eating foods rich in calcium and proteins, exercising, sitting and standing correctly, avoiding dangerous play, and seeking medical help after serious injury.",
      ],
      worked: {
        problem: "A pupil says the ribs are not important because they do not help us write. Explain two important functions of the ribs.",
        steps: [
          "Step 1. Identify where the ribs are found. They form a cage around the chest.",
          "Step 2. Think about the organs inside the chest. The heart and lungs are inside the rib cage.",
          "Step 3. State the protection function. Ribs protect the heart and lungs from injury.",
          "Step 4. State the breathing support function. Ribs help the chest expand and contract during breathing.",
        ],
        answer: "Answer: The ribs protect the heart and lungs and help in breathing movements.",
      },
      commonMistakes: [
        "Thinking muscles alone cause movement without bones and joints.",
        "Mixing up voluntary and involuntary muscles.",
        "Calling every joint a hinge joint.",
        "Forgetting that posture is part of caring for the muscular-skeletal system.",
      ],
      tryThis: {
        question: "Which joint is found at the shoulder?",
        choices: ["Hinge joint", "Ball-and-socket joint", "Pivot joint", "Fixed joint"],
        correct: 1,
        explanation: "The shoulder allows movement in many directions, so it is a ball-and-socket joint.",
      },
      writingTasks: [
        {
          title: "Observation task: Good posture and movement",
          prompt: "Observe how a learner sits, stands and carries a school bag. Explain how posture affects muscles and bones.",
          planningSteps: [
            "Name the body parts involved, such as backbone, shoulders, joints and muscles.",
            "Describe one good posture habit and one poor posture habit.",
            "Explain one possible effect of poor posture.",
            "Suggest a safe habit that protects the muscular-skeletal system.",
          ],
          checklist: [
            "Bones, joints and muscles are mentioned correctly.",
            "The explanation links posture to health.",
            "The advice is practical for a P7 learner.",
            "The answer avoids unsafe treatment advice and recommends adult help for injuries.",
          ],
          modelOpening: "Good posture helps the backbone and muscles support the body properly. A learner should sit upright and avoid carrying a heavy bag on one shoulder only.",
        },
      ],
      recap: [
        "The skeleton gives shape, support and protection.",
        "Muscles contract and relax to cause movement.",
        "Joints are places where bones meet.",
        "Good posture, exercise and balanced diet help keep bones and muscles healthy.",
      ],
    },
    quiz: [
      { q: "What is the main function of the skull?", choices: ["To digest food", "To protect the brain", "To pump blood", "To produce urine"], correct: 1, why: "The skull is a hard bony structure that protects the brain." },
      { q: "Which pair of bones is found in the forearm?", choices: ["Femur and tibia", "Radius and ulna", "Ribs and skull", "Pelvis and backbone"], correct: 1, why: "The radius and ulna are the two bones of the forearm." },
      { q: "A joint that allows movement like opening and closing a door is a:", choices: ["Hinge joint", "Pivot joint", "Fixed joint", "Gliding joint"], correct: 0, why: "Hinge joints, such as the elbow and knee, move mainly backwards and forwards." },
      { q: "Which of these is an involuntary muscle action?", choices: ["Writing", "Kicking a ball", "Movement of food in the intestines", "Clapping"], correct: 2, why: "Intestinal movement happens without direct control, so it is involuntary." },
      { q: "Which habit helps keep the muscular-skeletal system healthy?", choices: ["Poor sitting posture", "Eating a balanced diet", "Avoiding all exercise", "Carrying very heavy loads badly"], correct: 1, why: "A balanced diet supplies nutrients needed for strong bones and muscles." },
      { q: "What is a fracture?", choices: ["A broken bone", "A swollen muscle", "A type of joint", "A curved backbone only"], correct: 0, why: "A fracture is a break or crack in a bone." },
      { q: "Why are muscles attached to bones important?", choices: ["They make urine", "They help bones move", "They digest fats", "They filter blood"], correct: 1, why: "Muscles contract and relax, pulling on bones to cause movement." },
    ],
  },
  {
    id: "electricity-and-magnetism",
    themeId: "science-matter-energy",
    themeName: "Matter and Energy",
    title: "Electricity and magnetism",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Electricity and magnetism are used in homes, schools, hospitals, transport and communication. P7 learners need to understand simple circuits, magnets, safety, and how electricity and magnetism are connected.",
      learningObjectives: [
        "Identify sources and types of electricity.",
        "Draw and explain a simple electric circuit.",
        "Distinguish conductors and insulators.",
        "Explain properties and uses of magnets.",
        "Describe safety precautions when using electricity.",
      ],
      whatYouNeedToKnow: [
        "Electricity is a form of energy. Current electricity flows through a complete circuit, while static electricity is caused by electric charges building up on a surface.",
        "Sources of electricity include dry cells, accumulators, generators, dynamos, solar cells and mains electricity. In school circuits, dry cells are safer for demonstrations than mains electricity.",
        "A simple circuit needs a source of electricity, connecting wires, a switch and a device such as a bulb. The circuit must be complete for current to flow and for the bulb to light. If any connection is loose, the switch is open, or the cell is weak, the bulb may not light.",
        "Conductors allow electricity to pass through them easily. Most metals are good conductors. Insulators do not allow electricity to pass through them easily. Rubber, plastic and dry wood are common insulators. Insulators are used to cover wires and handles of electrical tools.",
        "A short circuit happens when current follows an unintended path with little resistance. It may cause overheating, fire or damage to appliances. Fuses, circuit breakers, correct wiring and avoiding overloaded sockets help to reduce danger.",
        "Magnets attract magnetic materials such as iron, steel, nickel and cobalt. A magnet has two poles, north and south. Like poles repel, while unlike poles attract. Magnetic force is strongest near the poles.",
        "Temporary magnets can be made by stroking, induction or using electricity. An electromagnet is made by winding insulated wire around a soft iron core and passing current through the wire. It loses magnetism when current is switched off.",
        "Electricity can be used to make temporary magnets, and magnetism can be used to generate electricity using a dynamo. This link is used in electric bells, generators, speakers, motors and many modern machines.",
      ],
      worked: {
        problem: "A bulb in a simple circuit does not light. Give three possible reasons.",
        steps: [
          "Step 1. Check whether the dry cell is working or placed correctly.",
          "Step 2. Check whether the circuit is complete. A loose wire can stop current from flowing.",
          "Step 3. Check whether the switch is open or closed. An open switch breaks the circuit.",
          "Step 4. Check whether the bulb is damaged or burnt out.",
        ],
        answer: "Answer: The bulb may fail to light because the cell is weak, the circuit is incomplete, the switch is open, or the bulb is damaged.",
      },
      commonMistakes: [
        "Thinking a bulb can light in an open circuit.",
        "Calling every material a conductor because it looks shiny.",
        "Forgetting that magnets have two poles.",
        "Thinking an electromagnet stays magnetic after current is switched off.",
        "Handling electricity with wet hands or damaged wires.",
      ],
      tryThis: {
        question: "Which material is the best electrical insulator?",
        choices: ["Copper", "Iron", "Aluminium", "Rubber"],
        correct: 3,
        explanation: "Rubber is an insulator, so it does not allow electricity to pass through easily.",
      },
      writingTasks: [
        {
          title: "Experiment plan: Making an electromagnet",
          prompt: "Plan a simple experiment to make a temporary magnet using a dry cell, insulated wire and an iron nail.",
          planningSteps: [
            "List the materials needed.",
            "Describe how to wind the wire around the nail and connect the dry cell.",
            "State what you will use to test whether the nail is magnetic.",
            "Give two safety precautions for using electricity.",
          ],
          checklist: [
            "The circuit is described as complete only during testing.",
            "The iron nail/core is included.",
            "The test uses small iron objects such as pins or paper clips.",
            "Electrical safety is clearly mentioned.",
          ],
          modelOpening: "To make an electromagnet, I would wind insulated copper wire around an iron nail and connect the wire ends briefly to a dry cell.",
        },
      ],
      recap: [
        "A complete circuit is needed for current to flow.",
        "Conductors allow current to pass; insulators do not.",
        "Magnets attract magnetic materials and have two poles.",
        "Electricity and magnetism are linked through electromagnets and dynamos.",
        "Fuses, insulation and avoiding overloaded sockets help prevent electrical accidents.",
        "Electrical safety is part of the topic, not an extra.",
      ],
    },
    quiz: [
      { q: "Which item is needed to open and close an electric circuit?", choices: ["Switch", "Ruler", "Magnet only", "Thermometer"], correct: 0, why: "A switch opens or closes a circuit to control current flow." },
      { q: "Which material is a good conductor of electricity?", choices: ["Plastic", "Rubber", "Copper", "Dry wood"], correct: 2, why: "Copper is a metal and a good electrical conductor." },
      { q: "What happens when like poles of two magnets are brought together?", choices: ["They repel", "They attract", "They disappear", "They produce water"], correct: 0, why: "Like poles repel, while unlike poles attract." },
      { q: "A complete path through which current flows is called a:", choices: ["Circuit", "Shadow", "Lens", "Joint"], correct: 0, why: "An electric circuit is a complete path for current." },
      { q: "Which is a source of electricity in a simple torch?", choices: ["Bulb", "Dry cell", "Switch", "Wire covering"], correct: 1, why: "The dry cell supplies electrical energy to the torch circuit." },
      { q: "Why are electric wires often covered with plastic?", choices: ["Plastic is a good conductor", "Plastic is an insulator", "Plastic makes current stronger", "Plastic is magnetic"], correct: 1, why: "Plastic insulates the wire and helps prevent electric shock." },
      { q: "Which device can use magnetism to generate electricity?", choices: ["Dynamo", "Mirror", "Periscope", "Lever"], correct: 0, why: "A dynamo uses movement and magnetism to generate electricity." },
    ],
  },
  {
    id: "energy-resources-environment",
    themeId: "science-environment",
    themeName: "The Environment",
    title: "Energy resources in the environment",
    estMinutes: 15,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: People use energy every day for cooking, lighting, transport, farming and industry. Learners need to know different energy resources, their sources, and how to use them safely and sustainably.",
      learningObjectives: [
        "Name different energy resources and their sources.",
        "Explain the importance of energy resources.",
        "Distinguish renewable and non-renewable energy resources.",
        "Describe safe and sustainable ways of using energy.",
      ],
      whatYouNeedToKnow: [
        "The sun is the major source of energy in the environment. Solar energy gives heat and light, helps plants make food, dries clothes and can be used by solar equipment.",
        "Water can provide energy through hydro-electric power, steam engines and tidal energy. Moving water can turn turbines to generate electricity.",
        "Fossil fuels include coal and petroleum. They are useful for transport, cooking, industry and electricity generation, but they can pollute the environment and can get finished because they take a very long time to form.",
        "Plants provide energy as food, firewood, charcoal, biofuel and biogas from plant residues. Animals can provide animal power and biogas from animal waste.",
        "Wind energy can be used to pump water, sail boats, dry things and generate electricity using wind turbines.",
        "Sustainable energy use means using energy wisely without destroying the environment. Examples include planting trees after cutting them, using improved stoves, using solar energy, and avoiding waste.",
      ],
      worked: {
        problem: "Classify these energy resources as renewable or non-renewable: solar energy, petroleum, wind energy and coal.",
        steps: [
          "Step 1. Renewable resources can be naturally replaced in a short time or continue to be available.",
          "Step 2. Solar energy and wind energy are renewable because the sun and wind continue to be available naturally.",
          "Step 3. Non-renewable resources take a very long time to form and can get finished.",
          "Step 4. Petroleum and coal are non-renewable fossil fuels.",
        ],
        answer: "Answer: Renewable: solar energy and wind energy. Non-renewable: petroleum and coal.",
      },
      commonMistakes: [
        "Mixing up an energy source with the energy resource itself.",
        "Thinking all fuels are renewable.",
        "Forgetting that energy use can harm the environment if not managed well.",
        "Ignoring local examples such as firewood, biogas and animal power.",
      ],
      tryThis: {
        question: "Which energy resource comes from animal waste?",
        choices: ["Biogas", "Petroleum", "Coal", "Tidal energy"],
        correct: 0,
        explanation: "Biogas can be produced from animal waste and plant residues.",
      },
      writingTasks: [
        {
          title: "Community application: Choosing an energy resource",
          prompt: "A rural school wants safer and cheaper energy for cooking or lighting. Recommend one energy resource and explain your choice.",
          planningSteps: [
            "Name the energy resource you recommend.",
            "State whether it is renewable or non-renewable.",
            "Explain two advantages for the school.",
            "Mention one environmental precaution or limitation.",
          ],
          checklist: [
            "The energy resource is correctly classified.",
            "Advantages are practical and local.",
            "Environmental effects are considered.",
            "The recommendation is clear.",
          ],
          modelOpening: "I would recommend solar energy for lighting because sunlight is renewable and solar panels can help pupils read without using kerosene lamps.",
        },
      ],
      recap: [
        "The sun is a major source of energy.",
        "Energy resources include solar, water, fossil fuels, plants, animals and wind.",
        "Renewable resources can be replaced naturally; non-renewable resources can get finished.",
        "Energy should be used safely and sustainably.",
      ],
    },
    quiz: [
      { q: "Which is the major source of energy in the environment?", choices: ["The sun", "A dry cell", "A candle", "A switch"], correct: 0, why: "The sun gives heat and light and supports many energy processes on earth." },
      { q: "Which of these is a fossil fuel?", choices: ["Wind", "Coal", "Solar energy", "Animal power"], correct: 1, why: "Coal is a fossil fuel formed from remains of ancient living things over a long time." },
      { q: "Biogas can be made from:", choices: ["Clean stones only", "Animal waste and plant residues", "Glass and metal", "Dry sand"], correct: 1, why: "Biogas can be produced when animal waste and plant residues decompose without oxygen." },
      { q: "Which energy resource is renewable?", choices: ["Petroleum", "Coal", "Wind", "Kerosene"], correct: 2, why: "Wind continues to be naturally available, so wind energy is renewable." },
      { q: "What is one danger of careless use of firewood?", choices: ["It increases forests", "It may lead to deforestation", "It produces rain", "It makes soil deeper"], correct: 1, why: "Cutting trees without replacing them can cause deforestation." },
      { q: "Hydro-electricity is produced using energy from:", choices: ["Moving water", "Dry paper", "A mirror", "A magnet alone"], correct: 0, why: "Moving water can turn turbines to generate hydro-electricity." },
      { q: "Which practice shows sustainable energy use?", choices: ["Wasting fuel", "Planting trees after cutting them", "Leaving lights on all day", "Burning all bushes"], correct: 1, why: "Replacing trees helps protect the environment and maintain future wood fuel sources." },
    ],
  },
  {
    id: "simple-machines-friction",
    themeId: "science-matter-energy",
    themeName: "Matter and Energy",
    title: "Simple machines and friction",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Simple machines help people do work more easily. Friction can be useful or troublesome, so learners need to know when to increase it and when to reduce it.",
      learningObjectives: [
        "Identify common simple machines used in daily life.",
        "Explain how simple machines make work easier.",
        "Describe useful and nuisance friction.",
        "Explain ways of increasing and reducing friction.",
      ],
      whatYouNeedToKnow: [
        "A machine is a device that makes work easier. Simple machines include levers, inclined planes, wedges, screws, pulleys, and wheels and axles. A machine may make work easier by reducing effort, changing the direction of effort, increasing speed, or helping work to be done more safely.",
        "A lever is a rigid bar that turns about a fixed point called a fulcrum. Examples include a seesaw, crowbar, bottle opener, wheelbarrow and pair of scissors. In a lever, the load is the object being moved and the effort is the force applied to move it.",
        "The principle of moments says that a lever balances when clockwise moment equals anticlockwise moment. Moment is found by multiplying force by distance from the fulcrum. A small effort can lift a bigger load if it acts farther from the fulcrum.",
        "Mechanical advantage compares the load moved with the effort used. Mechanical advantage = load ÷ effort. If a machine has a high mechanical advantage, it helps a small effort move a larger load, although the effort may move through a longer distance.",
        "An inclined plane is a sloping surface that helps move loads up or down more easily. Ramps and slopes are examples. A wedge is like two inclined planes joined together, such as an axe or knife edge. A screw is an inclined plane wound around a cylinder and is used in screws, bottle tops and some jacks.",
        "A pulley uses a wheel and rope to lift loads or change the direction of effort. A fixed pulley mainly changes the direction of effort, while movable pulleys can reduce the effort needed. A wheel and axle helps movement, as seen in bicycles, cars, wheelbarrows and doorknobs.",
        "Friction is a force that opposes motion between surfaces in contact. It can be useful, for example in walking, writing, lighting a match and braking. It can also be a nuisance because it causes wear, heat, noise and wasted energy in machines.",
        "Friction can be increased by making surfaces rougher, adding treads, using grip material or pressing surfaces together. It can be reduced by lubrication, smoothing surfaces, using rollers or ball bearings, and streamlining objects moving through air or water.",
      ],
      worked: {
        problem: "A box is too heavy to lift directly into a truck. Which simple machine can help and why?",
        steps: [
          "Step 1. Identify the problem. The box needs to move from the ground to a higher level.",
          "Step 2. Choose a simple machine for moving a load up to a height. An inclined plane can be used.",
          "Step 3. Explain why it helps. A ramp allows the load to be pushed or pulled gradually instead of lifted straight up.",
        ],
        answer: "Answer: Use an inclined plane or ramp because it makes it easier to move the heavy box into the truck.",
      },
      commonMistakes: [
        "Thinking simple machines remove work completely instead of making work easier.",
        "Confusing load, effort and fulcrum in lever questions.",
        "Forgetting that a fixed pulley mainly changes direction of effort.",
        "Thinking friction is always bad.",
        "Saying oil increases friction when it usually reduces friction.",
      ],
      tryThis: {
        question: "Which simple machine is used in a flagpole to raise a flag?",
        choices: ["Pulley", "Wedge", "Screw", "Inclined plane"],
        correct: 0,
        explanation: "A flagpole uses a pulley and rope to raise and lower the flag.",
      },
      writingTasks: [
        {
          title: "Application task: Choosing a simple machine",
          prompt: "A pupil wants to lift a heavy box onto a veranda. Choose a simple machine that can help and explain how it works.",
          planningSteps: [
            "Name a suitable simple machine.",
            "Identify the load and effort.",
            "Explain how the machine makes work easier.",
            "State one safety precaution.",
          ],
          checklist: [
            "The chosen machine fits the problem.",
            "Load and effort are identified correctly.",
            "The explanation uses correct Science vocabulary.",
            "Friction or safety is considered where relevant.",
          ],
          modelOpening: "An inclined plane can help lift the heavy box because the pupil can push it up a sloping plank instead of lifting it straight up.",
        },
      ],
      recap: [
        "Simple machines make work easier.",
        "Examples include levers, ramps, wedges, screws, pulleys, wheels and axles.",
        "Mechanical advantage compares load with effort.",
        "Friction opposes motion between surfaces.",
        "Friction can be useful or a nuisance depending on the situation.",
      ],
    },
    quiz: [
      { q: "Which is an example of a lever?", choices: ["Seesaw", "Mirror", "Dry cell", "Lens"], correct: 0, why: "A seesaw is a lever because it turns about a fulcrum." },
      { q: "A ramp is an example of a:", choices: ["Pulley", "Inclined plane", "Magnet", "Circuit"], correct: 1, why: "A ramp is a sloping surface, so it is an inclined plane." },
      { q: "Which simple machine uses a wheel and rope?", choices: ["Wedge", "Pulley", "Screw", "Lever only"], correct: 1, why: "A pulley uses a wheel and rope to lift or move loads." },
      { q: "Which situation shows useful friction?", choices: ["Machine parts wearing out", "Shoes gripping the ground while walking", "Engine overheating", "Door hinge squeaking"], correct: 1, why: "Friction between shoes and ground helps us walk without slipping." },
      { q: "Which method reduces friction?", choices: ["Adding oil", "Making a tyre rougher", "Adding treads", "Walking on dry soil"], correct: 0, why: "Oil acts as a lubricant and reduces friction between moving parts." },
      { q: "A knife edge is an example of a:", choices: ["Wedge", "Pulley", "Wheel and axle", "Circuit"], correct: 0, why: "A wedge has a sharp edge and is used for cutting or splitting." },
      { q: "Why is friction sometimes called a nuisance force?", choices: ["It always helps movement", "It can cause wear and waste energy", "It produces food", "It removes gravity"], correct: 1, why: "Friction can cause wear, heat and wasted energy in machines." },
    ],
  },
  {
    id: "excretory-system",
    themeId: "science-human-body",
    themeName: "Human Body",
    title: "Excretory system",
    estMinutes: 16,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: The body produces waste materials that must be removed to stay healthy. P7 learners need to know the excretory organs, what each removes, and how to care for them.",
      learningObjectives: [
        "Name the main excretory organs of the body.",
        "Describe the functions of the skin, kidneys and lungs as excretory organs.",
        "Explain how to care for the excretory system.",
        "Identify common diseases and disorders linked to the skin, kidneys and lungs.",
      ],
      whatYouNeedToKnow: [
        "Excretion is the removal of waste products made by body activities. It is different from egestion, which is removal of undigested food from the alimentary canal.",
        "The main excretory organs include the kidneys, skin, lungs and liver. The kidneys remove excess water, salts and urea in urine. The skin removes sweat, which contains water, salts and small amounts of urea.",
        "The lungs remove carbon dioxide and water vapour during breathing out. The liver helps remove harmful substances from the blood and changes excess amino acids into urea.",
        "The urinary system includes the kidneys, ureters, urinary bladder and urethra. The kidneys filter blood to form urine. The ureters carry urine to the bladder, the bladder stores urine, and the urethra carries urine out of the body.",
        "The skin protects the body, helps regulate body temperature, and removes sweat. Skin problems include ringworm, scabies, wounds and burns. Kidney problems may be caused by infection, too little clean water, or harmful substances.",
        "Good habits include drinking enough safe water, eating a balanced diet, bathing regularly, avoiding drug abuse, using toilets properly, and seeking medical help when there is pain or blood in urine.",
      ],
      worked: {
        problem: "Explain the path followed by urine from where it is formed until it leaves the body.",
        steps: [
          "Step 1. Urine is formed in the kidneys when blood is filtered.",
          "Step 2. Urine moves from the kidneys through the ureters.",
          "Step 3. It is stored in the urinary bladder.",
          "Step 4. It leaves the body through the urethra.",
        ],
        answer: "Answer: Kidneys → ureters → urinary bladder → urethra.",
      },
      commonMistakes: [
        "Confusing excretion with egestion.",
        "Thinking only the kidneys excrete waste.",
        "Forgetting that lungs remove carbon dioxide.",
        "Calling ureters and urethra the same thing.",
      ],
      tryThis: {
        question: "Which waste product is mainly removed by the lungs?",
        choices: ["Urine", "Carbon dioxide", "Sweat", "Undigested food"],
        correct: 1,
        explanation: "The lungs remove carbon dioxide and water vapour during breathing out.",
      },
      writingTasks: [
        {
          title: "Explanation task: Keeping excretory organs healthy",
          prompt: "Explain how a P7 learner can help keep the kidneys, skin and lungs healthy.",
          planningSteps: [
            "Name at least three excretory organs.",
            "State the waste each organ removes.",
            "Give one healthy habit for each organ.",
            "Explain why drinking clean water and avoiding harmful substances matters.",
          ],
          checklist: [
            "Organs are matched to correct wastes.",
            "Habits are safe and age-appropriate.",
            "Excretion is not confused with egestion.",
            "The explanation is clear and practical.",
          ],
          modelOpening: "The kidneys, skin and lungs remove wastes from the body. We can help them work well by drinking clean water, bathing regularly and breathing clean air.",
        },
      ],
      recap: [
        "Excretion removes waste products made by body activities.",
        "Kidneys form urine by filtering blood.",
        "Skin removes sweat and helps control body temperature.",
        "Lungs remove carbon dioxide and water vapour.",
        "Safe water, cleanliness and medical care help protect the excretory system.",
      ],
    },
    quiz: [
      { q: "What is excretion?", choices: ["Removal of body waste products", "Eating food", "Breathing in oxygen only", "Breaking food by teeth"], correct: 0, why: "Excretion is the removal of waste products made by body activities." },
      { q: "Which organ forms urine?", choices: ["Kidney", "Heart", "Stomach", "Eye"], correct: 0, why: "The kidneys filter blood and form urine." },
      { q: "What carries urine from the kidneys to the bladder?", choices: ["Urethra", "Ureters", "Windpipe", "Intestine"], correct: 1, why: "The ureters carry urine from the kidneys to the urinary bladder." },
      { q: "Which waste is removed through the skin?", choices: ["Sweat", "Faeces", "Oxygen", "Saliva"], correct: 0, why: "Sweat is removed through the skin and contains water, salts and small amounts of urea." },
      { q: "Which organ removes carbon dioxide from the body?", choices: ["Lungs", "Kidneys", "Bladder", "Teeth"], correct: 0, why: "The lungs remove carbon dioxide during breathing out." },
      { q: "Which habit helps care for the kidneys?", choices: ["Drinking enough safe water", "Taking unknown drugs", "Holding urine for very long", "Avoiding all liquids"], correct: 0, why: "Safe water helps the kidneys remove wastes properly." },
      { q: "What is the bladder's main function?", choices: ["To form urine", "To store urine", "To pump blood", "To digest food"], correct: 1, why: "The urinary bladder stores urine before it leaves the body." },
    ],
  },
  {
    id: "light-energy",
    themeId: "science-matter-energy",
    themeName: "Matter and Energy",
    title: "Light energy",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Light helps us see and understand many natural phenomena. P7 learners need to know sources of light, how light travels, shadows, reflection, refraction, lenses, cameras and the human eye.",
      learningObjectives: [
        "Name natural and artificial sources of light.",
        "Explain how light travels and forms shadows.",
        "Describe reflection and refraction of light.",
        "Compare a lens camera with the human eye.",
        "State common eye defects, eye diseases and ways of caring for the eye.",
      ],
      whatYouNeedToKnow: [
        "Light is a form of energy that enables us to see. Natural sources of light include the sun, stars, lightning and fireflies. Artificial sources include bulbs, candles, torches, lamps and fires made by people.",
        "Light travels in straight lines. A ray is a single path of light, while a beam is a group of rays. When an opaque object blocks light, a shadow is formed. The size of a shadow changes when the object or light source moves nearer or farther away.",
        "Shadows help explain eclipses and pinhole camera images. A solar eclipse happens when the moon blocks sunlight from reaching part of the earth. A lunar eclipse happens when the earth blocks sunlight from reaching the moon. A pinhole camera forms an inverted image because light travels in straight lines through a small hole.",
        "Materials affect light differently. Transparent materials allow most light to pass through. Translucent materials allow some light through but not a clear image. Opaque materials do not allow light to pass through. Smooth shiny surfaces reflect light better than dull rough surfaces.",
        "Reflection is the bouncing back of light from a surface. Plane mirrors form upright images that are the same size as the object, the same distance behind the mirror as the object is in front, and laterally inverted. A periscope uses two plane mirrors to see over or around obstacles.",
        "Refraction is the bending of light as it passes from one medium to another. Refraction helps explain why a stick in water looks bent and how lenses work. Dispersion splits white light into colours, as seen in a rainbow.",
        "Convex lenses can converge light and are used in magnifying glasses, cameras and the eye. A simple lens camera forms a real inverted image on a screen or film. The human eye works like a camera: the lens focuses light on the retina, the iris controls light entering the eye, and the optic nerve carries messages to the brain.",
        "Common eye defects include short sight and long sight. Short sight is corrected using concave lenses, while long sight is corrected using convex lenses. Eye diseases and disorders include conjunctivitis, cataracts and eye injuries. Eyes should be protected from sharp objects, bright light, dust and infections, and serious eye problems should be taken to a health worker.",
      ],
      worked: {
        problem: "A pencil placed in a glass of water appears bent. Which property of light explains this?",
        steps: [
          "Step 1. Light moves from water into air before reaching the eye.",
          "Step 2. When light moves from one medium to another, it changes direction.",
          "Step 3. This bending of light is called refraction.",
        ],
        answer: "Answer: The pencil appears bent because of refraction of light.",
      },
      commonMistakes: [
        "Thinking light can bend around corners without reflection or refraction.",
        "Mixing up reflection and refraction.",
        "Calling transparent and translucent materials the same.",
        "Forgetting that a shadow forms when an opaque object blocks light.",
        "Confusing convex and concave lenses when correcting eye defects.",
        "Forgetting that a pinhole camera forms an inverted image.",
      ],
      tryThis: {
        question: "Which material is opaque?",
        choices: ["Clear glass", "Clean water", "Wood", "Thin tracing paper"],
        correct: 2,
        explanation: "Wood does not allow light to pass through, so it is opaque.",
      },
      writingTasks: [
        {
          title: "Ray diagram explanation: Reflection and shadows",
          prompt: "Describe how light travels to form a shadow or reflect from a mirror.",
          planningSteps: [
            "State that light travels in straight lines.",
            "Name the source of light and the object or mirror.",
            "Explain what blocks light or reflects it.",
            "Use correct words such as ray, reflection, opaque, transparent and shadow.",
          ],
          checklist: [
            "Straight-line travel of light is included.",
            "Reflection or shadow formation is explained correctly.",
            "Correct light vocabulary is used.",
            "The explanation matches the diagram or situation.",
          ],
          modelOpening: "Light travels in straight lines. When an opaque object blocks light from a torch, a shadow is formed behind the object.",
        },
      ],
      recap: [
        "Light travels in straight lines.",
        "Opaque objects form shadows by blocking light.",
        "Reflection is bouncing back of light.",
        "Refraction is bending of light between media.",
        "The eye uses a lens to focus light on the retina.",
        "Short sight and long sight are corrected with different lenses.",
        "Eye care includes cleanliness, protection from injury and treatment by a health worker.",
      ],
    },
    quiz: [
      { q: "Which is a natural source of light?", choices: ["Sun", "Torch", "Electric bulb", "Candle"], correct: 0, why: "The sun is a natural source of light." },
      { q: "How does light usually travel?", choices: ["In straight lines", "Only in circles", "Only through metal", "Backwards only"], correct: 0, why: "Light travels in straight lines unless reflected or refracted." },
      { q: "What type of material does not allow light to pass through?", choices: ["Transparent", "Translucent", "Opaque", "Magnetic"], correct: 2, why: "Opaque materials block light." },
      { q: "Reflection means:", choices: ["Bouncing back of light", "Bending of light", "Making urine", "Changing water into steam"], correct: 0, why: "Reflection is the bouncing back of light from a surface." },
      { q: "What causes a pencil in water to appear bent?", choices: ["Friction", "Refraction", "Excretion", "Magnetism"], correct: 1, why: "Refraction bends light as it moves between water and air." },
      { q: "Which part of the eye receives the focused image?", choices: ["Retina", "Ribs", "Kidney", "Ureter"], correct: 0, why: "The retina receives the focused image in the eye." },
      { q: "A periscope mainly uses:", choices: ["Mirrors", "Kidneys", "Magnets only", "Friction"], correct: 0, why: "A periscope uses mirrors to reflect light." },
    ],
  },
  {
    id: "interdependence-environment",
    themeId: "science-environment",
    themeName: "The Environment",
    title: "Interdependence of things in the environment",
    estMinutes: 17,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Living and non-living things in the environment depend on one another. Understanding interdependence helps learners protect the environment and use resources responsibly.",
      learningObjectives: [
        "Name components of the environment.",
        "Explain how plants, animals and non-living things depend on one another.",
        "Describe agroforestry and its importance.",
        "Explain ways of caring for trees and managing wood projects.",
      ],
      whatYouNeedToKnow: [
        "The environment includes living things such as plants and animals, and non-living things such as air, water, soil, rocks and sunlight.",
        "Animals depend on plants for food, shelter, oxygen and materials. Plants may depend on animals for pollination, seed dispersal, manure and carbon dioxide.",
        "Animals also depend on other animals for food, protection, cleaning, transport and other relationships. Plants may depend on other plants for support, shade or protection.",
        "Living things depend on non-living things. Plants need water, air, soil and sunlight to grow. Animals need air, water and sometimes soil or water bodies as habitats. Non-living things also benefit from living things, for example dead plants and animals add humus to soil.",
        "Agroforestry is the practice of growing trees together with crops or rearing animals on the same land. It helps conserve soil, provide shade, produce firewood, improve fertility, and reduce wind damage.",
        "Trees in agroforestry should be cared for by watering, protecting seedlings, pruning, pollarding, coppicing, lopping carefully, and harvesting responsibly.",
      ],
      worked: {
        problem: "Explain two ways animals depend on plants and two ways plants depend on animals.",
        steps: [
          "Step 1. Animals depend on plants for food such as fruits, leaves and seeds.",
          "Step 2. Animals also depend on plants for oxygen and shelter.",
          "Step 3. Plants depend on animals for pollination when insects move pollen from flower to flower.",
          "Step 4. Plants can also depend on animals for seed dispersal or manure.",
        ],
        answer: "Answer: Animals depend on plants for food, oxygen and shelter. Plants depend on animals for pollination, seed dispersal and manure.",
      },
      commonMistakes: [
        "Thinking only animals depend on plants, not the other way round.",
        "Forgetting non-living things like air, soil and water.",
        "Confusing agroforestry with ordinary forest cutting.",
        "Ignoring responsible harvesting of trees.",
      ],
      tryThis: {
        question: "Which is an example of agroforestry?",
        choices: ["Growing crops and trees together", "Burning all trees", "Keeping soil bare", "Throwing waste in a wetland"],
        correct: 0,
        explanation: "Agroforestry involves growing trees together with crops or animals on the same land.",
      },
      writingTasks: [
        {
          title: "Food chain task: Interdependence in a garden",
          prompt: "Construct and explain a simple food chain found in a school garden.",
          planningSteps: [
            "Start with a green plant as the producer.",
            "Add a plant eater and then a predator if possible.",
            "Use arrows to show the direction of energy flow.",
            "Explain what may happen if one organism is removed.",
          ],
          checklist: [
            "The food chain starts with a producer.",
            "Arrows show energy flow correctly.",
            "Producer, consumer and predator are used correctly where possible.",
            "The explanation shows interdependence.",
          ],
          modelOpening: "Grass → grasshopper → chicken is a simple food chain. The grass makes its own food, the grasshopper feeds on grass, and the chicken may feed on the grasshopper.",
        },
      ],
      recap: [
        "The environment has living and non-living components.",
        "Plants, animals and non-living things depend on one another.",
        "Agroforestry combines trees with crops or animals.",
        "Responsible tree care protects the environment.",
      ],
    },
    quiz: [
      { q: "Which is a non-living component of the environment?", choices: ["Goat", "Mango tree", "Water", "Grasshopper"], correct: 2, why: "Water is non-living but important in the environment." },
      { q: "How do animals help some plants reproduce?", choices: ["By pollination and seed dispersal", "By removing all soil", "By blocking sunlight", "By making rocks"], correct: 0, why: "Animals such as insects can pollinate flowers, and animals can disperse seeds." },
      { q: "Plants give animals:", choices: ["Oxygen and food", "Plastic and iron", "Petroleum only", "Electric circuits"], correct: 0, why: "Plants provide oxygen, food, shelter and materials to animals." },
      { q: "What is agroforestry?", choices: ["Growing trees with crops or animals", "Cutting all trees", "Fishing only", "Making mirrors"], correct: 0, why: "Agroforestry combines trees with crops or animal rearing on the same land." },
      { q: "Which practice helps care for trees?", choices: ["Protecting seedlings", "Ring barking every tree", "Burning young trees", "Leaving animals to destroy seedlings"], correct: 0, why: "Protecting seedlings helps trees grow well." },
      { q: "Dead plants and animals can improve soil by adding:", choices: ["Humus", "Plastic", "Glass", "Electricity"], correct: 0, why: "Decayed plant and animal remains add humus to soil." },
      { q: "Which statement is true?", choices: ["Living things never need non-living things", "Plants need water, air and sunlight", "Animals do not need oxygen", "Soil is a living animal"], correct: 1, why: "Plants need water, air, sunlight and soil nutrients for growth." },
    ],
  },
  {
    id: "population-and-health",
    themeId: "science-community-health",
    themeName: "The Community, Population and Family Life",
    title: "Population and health",
    estMinutes: 17,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Health problems affect homes, schools and communities. P7 learners need to identify common sicknesses, understand social problems, collect simple health information, and take part in health activities.",
      learningObjectives: [
        "Name common sicknesses in homes and communities.",
        "Describe causes and control of common sicknesses.",
        "Identify anti-social behaviour and health risks among young people using respectful, safety-focused language.",
        "Explain simple health surveys and activities of health clubs.",
      ],
      whatYouNeedToKnow: [
        "Common sicknesses in homes and communities include malaria, diarrhoea, coughs, measles, skin infections, worms and eye infections. Causes may include germs, mosquitoes, unsafe water, poor sanitation, poor feeding, overcrowding and lack of immunisation.",
        "Community health improves when people use safe water, latrines, proper waste disposal, mosquito nets, immunisation, balanced diet, hand washing and early treatment. Prevention is better than waiting until many people are sick.",
        "Different sicknesses need different control measures. Malaria can be reduced by clearing stagnant water, using mosquito nets and seeking treatment early. Diarrhoea can be reduced by safe water, hand washing, proper latrine use and covering food. Worms can be controlled by wearing shoes, washing hands and taking deworming medicine when advised by health workers.",
        "Young people may face social problems such as drug abuse, theft, violence, bad peer pressure, unsafe sexual behaviour, school dropout and other anti-social behaviour. Lessons on these issues should be respectful, safety-focused and guided by a trusted teacher, parent or health worker. These problems can harm health, education and community peace.",
        "A health concern can be addressed through health education, cleaning campaigns, reporting dangers, using health services, joining health clubs, and encouraging safe behaviour. Learners should report danger, abuse, sickness or pressure to trusted adults rather than handling serious problems alone.",
        "Demography is the study of human population. Simple health surveys collect information about people, homes, sicknesses, sanitation, available health services and community needs. Survey questions should be clear, respectful and useful for solving a health problem.",
        "A simple health survey has steps: choose the health problem, plan questions, collect information, organise the data, discuss findings, report results and take action. Results can be shown in tables, tally charts, bar graphs or short reports.",
        "Health clubs help learners promote hygiene, first aid, environmental cleanliness, disease prevention and health education in the school and community. They may organise hand-washing campaigns, compound cleaning, safe-water messages, sanitation checks and peer education with teacher guidance.",
      ],
      worked: {
        problem: "A village has many cases of diarrhoea. Suggest three questions learners can ask in a simple health survey.",
        steps: [
          "Step 1. Ask about water because diarrhoea can spread through unsafe water: Where do families get drinking water?",
          "Step 2. Ask about sanitation: Do homes have and use latrines?",
          "Step 3. Ask about hygiene: Do people wash hands after using the latrine and before eating?",
          "Step 4. Ask about treatment if needed: Have sick people visited a health worker?",
        ],
        answer: "Answer: Useful survey questions can ask about water source, latrine use, hand washing, and treatment from health workers.",
      },
      commonMistakes: [
        "Thinking health is only the work of hospitals and not the community.",
        "Listing sicknesses without their causes or control measures.",
        "Collecting survey information without organising or reporting it.",
        "Asking survey questions that are unclear, disrespectful or not useful for solving the problem.",
        "Ignoring prevention activities such as hand washing and immunisation.",
        "Using insulting or unsafe language when discussing sensitive health and social problems.",
      ],
      tryThis: {
        question: "Which activity can a school health club do?",
        choices: ["Promote hand washing", "Encourage dirty compounds", "Hide sickness reports", "Stop pupils from using latrines"],
        correct: 0,
        explanation: "A health club can promote hand washing, cleanliness, disease prevention and health education.",
      },
      writingTasks: [
        {
          title: "Health advice task: Preventing disease in a community",
          prompt: "Write health advice for a village that wants to reduce disease and improve population health.",
          planningSteps: [
            "Name two common causes of disease spread.",
            "Give practical prevention methods such as clean water, latrines, immunisation or mosquito control.",
            "Mention the role of parents, teachers or health workers.",
            "Use respectful, age-appropriate language.",
          ],
          checklist: [
            "Advice is safe and practical.",
            "Disease prevention methods are scientifically correct.",
            "The answer encourages trusted adult or health-worker guidance.",
            "The wording is respectful and not stigmatizing.",
          ],
          modelOpening: "A community can improve health by keeping water clean, using latrines properly, sleeping under mosquito nets and visiting health workers for advice and immunisation.",
        },
      ],
      recap: [
        "Common sicknesses have causes and control measures.",
        "Community health improves through prevention and safe habits.",
        "Anti-social behaviour and unsafe choices can damage health and education.",
        "Simple surveys help communities identify health problems.",
        "Survey results should be organised before action is planned.",
        "Health clubs support school and community health activities.",
      ],
    },
    quiz: [
      { q: "Which disease is commonly spread by mosquitoes?", choices: ["Malaria", "Rickets", "Fracture", "Short sight"], correct: 0, why: "Malaria is spread by infected mosquitoes." },
      { q: "Which practice helps prevent diarrhoea?", choices: ["Drinking unsafe water", "Hand washing with soap", "Open defecation", "Leaving food uncovered"], correct: 1, why: "Hand washing with soap helps prevent germs that cause diarrhoea." },
      { q: "What is demography?", choices: ["Study of human population", "Study of mirrors", "Study of magnets only", "Study of joints"], correct: 0, why: "Demography is the study of human population." },
      { q: "Which is an anti-social behaviour?", choices: ["Helping clean a compound", "Stealing", "Reporting sickness", "Using a latrine"], correct: 1, why: "Stealing harms other people and the community, so it is anti-social behaviour." },
      { q: "Why are health surveys useful?", choices: ["They help identify health problems", "They stop all learning", "They create sickness", "They hide community needs"], correct: 0, why: "Health surveys collect information that helps identify and address health problems." },
      { q: "Which activity addresses a health concern?", choices: ["Cleaning stagnant water", "Throwing rubbish in wells", "Sharing dirty cups", "Ignoring sick children"], correct: 0, why: "Removing stagnant water helps reduce mosquito breeding and disease." },
      { q: "Which is a cause of many common sicknesses?", choices: ["Poor sanitation", "Clean water", "Balanced diet", "Immunisation"], correct: 0, why: "Poor sanitation can spread germs and cause sickness." },
    ],
  },
];

export function getScienceTopic(id: string): Topic | undefined {
  return SCIENCE_TOPICS.find((topic) => topic.id === id);
}
