import type { Topic } from "@/lib/topics";

export const SOCIAL_TOPICS: Topic[] = [
  {
    id: "location-of-africa",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Location of Africa on the map of the world",
    estMinutes: 16,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: P7 Social Studies begins by placing Africa correctly on the world map. Learners need to use latitudes, longitudes, continents, surrounding water bodies, regions, countries and capitals.",
      learningObjectives: [
        "Locate Africa on a world map using latitudes and longitudes.",
        "Name the continents of the world and compare their sizes.",
        "Identify water bodies that surround Africa.",
        "Name regions of Africa, countries in those regions and capital cities.",
      ],
      whatYouNeedToKnow: [
        "Africa is the second largest continent after Asia. It lies mostly between the Tropic of Cancer and the Tropic of Capricorn, and it is crossed by the Equator, the Prime Meridian and the Tropic of Cancer and Capricorn.",
        "Lines of latitude run from east to west and help locate places north or south of the Equator. Lines of longitude run from north to south and help locate places east or west of the Prime Meridian.",
        "Africa is surrounded by the Mediterranean Sea to the north, the Red Sea and Indian Ocean to the east, the Atlantic Ocean to the west, and the Southern Ocean area towards the south.",
        "Africa is commonly grouped into North Africa, West Africa, East Africa, Central Africa and Southern Africa. Uganda is in East Africa.",
        "Knowing countries and capitals helps learners read maps, follow news and understand cooperation among African states.",
      ],
      worked: {
        problem: "A learner says Uganda is in West Africa because it is west of Kenya. Correct the statement.",
        steps: [
          "Step 1. Remember that African regions are not decided by comparing only two neighbouring countries.",
          "Step 2. Uganda is part of the East African region.",
          "Step 3. Kenya, Tanzania, Rwanda, Burundi, South Sudan and Uganda are commonly studied as East African neighbours.",
        ],
        answer: "Answer: Uganda is in East Africa, even though it lies west of Kenya.",
      },
      commonMistakes: [
        "Confusing lines of latitude with lines of longitude.",
        "Thinking Africa is the largest continent instead of the second largest.",
        "Mixing up oceans and seas around Africa.",
        "Placing Uganda in the wrong African region.",
      ],
      tryThis: {
        question: "Which major line of latitude crosses Africa near the middle?",
        choices: ["Equator", "Prime Meridian", "International Date Line", "Greenwich line only"],
        correct: 0,
        explanation: "The Equator is a line of latitude and crosses Africa near the middle.",
      },
      writingTasks: [
        {
          title: "Map task: Locating Africa",
          prompt: "Use a world map or globe to describe the location of Africa using nearby oceans, continents and major lines of latitude/longitude.",
          planningSteps: [
            "Name the oceans around Africa.",
            "Name nearby continents north, east and north-east of Africa.",
            "Mention the Equator, Tropics or Prime Meridian where relevant.",
            "Use compass directions such as north, south, east and west.",
          ],
          checklist: [
            "Oceans and neighbouring continents are named correctly.",
            "Compass directions are used accurately.",
            "Major imaginary lines are mentioned where useful.",
            "The description is clear enough for someone to find Africa on a map.",
          ],
          modelOpening: "Africa lies south of Europe and south-west of Asia. It is bordered by the Atlantic Ocean to the west and the Indian Ocean to the east.",
        },
      ],
      recap: [
        "Africa is the second largest continent.",
        "Latitudes and longitudes help locate places.",
        "Africa has five commonly studied regions.",
        "Uganda is in East Africa.",
      ],
    },
    quiz: [
      { q: "Which continent is the second largest in the world?", choices: ["Africa", "Europe", "Australia", "Antarctica"], correct: 0, why: "Africa is the second largest continent after Asia." },
      { q: "Which line of latitude divides the earth into northern and southern hemispheres?", choices: ["Equator", "Prime Meridian", "Tropic of Cancer only", "International Date Line"], correct: 0, why: "The Equator divides the earth into northern and southern hemispheres." },
      { q: "Which ocean lies to the west of Africa?", choices: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correct: 0, why: "The Atlantic Ocean is west of Africa." },
      { q: "Uganda belongs to which African region?", choices: ["East Africa", "North Africa", "West Africa", "Southern Africa only"], correct: 0, why: "Uganda is studied as an East African country." },
      { q: "Lines of longitude help locate places:", choices: ["East or west", "Only above clouds", "Only in lakes", "By population size"], correct: 0, why: "Longitudes locate places east or west of the Prime Meridian." },
      { q: "Which sea is north of Africa?", choices: ["Mediterranean Sea", "Caspian Sea", "Caribbean Sea", "Baltic Sea"], correct: 0, why: "The Mediterranean Sea lies north of Africa." },
      { q: "What is a capital city?", choices: ["Main administrative city of a country", "Any village", "A mountain", "A river mouth"], correct: 0, why: "A capital city is the main administrative city of a country." },
    ],
  },
  {
    id: "physical-features-of-africa",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Physical features of Africa",
    estMinutes: 17,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Africa's mountains, rivers, lakes, plateaus, rift valleys and coastal plains influence settlement, transport, farming, climate and tourism.",
      learningObjectives: [
        "Name and locate major physical features of Africa.",
        "Explain how some physical features are formed.",
        "Describe the importance of physical features to people.",
        "Relate physical features to settlement and economic activities.",
      ],
      whatYouNeedToKnow: [
        "Physical features are natural features found on the earth's surface. Examples in Africa include mountains, highlands, rivers, lakes, plateaus, rift valleys, deserts and coastal plains.",
        "Important mountains include Kilimanjaro, Kenya, Rwenzori and Atlas. Important rivers include the Nile, Congo, Niger and Zambezi. Important lakes include Victoria, Tanganyika, Malawi and Chad.",
        "The Great Rift Valley is a long depression formed by earth movements. Rift valley lakes are often long and deep, such as Lake Tanganyika.",
        "Physical features are important for fishing, farming, transport, hydro-electric power, tourism, mining and settlement. They can also create challenges such as barriers to transport or flooding.",
      ],
      worked: {
        problem: "Give two ways a river can be useful to people in Africa.",
        steps: [
          "Step 1. Think of direct uses: people may get water and fish from rivers.",
          "Step 2. Think of economic uses: rivers can support irrigation, transport and hydro-electric power.",
          "Step 3. Give clear examples instead of one-word answers.",
        ],
        answer: "Answer: A river can provide water for irrigation and can be used to generate hydro-electric power.",
      },
      commonMistakes: [
        "Calling man-made features physical features.",
        "Confusing Lake Victoria with River Nile.",
        "Forgetting that physical features can be useful and challenging.",
        "Mixing up mountains and highlands.",
      ],
      tryThis: {
        question: "Which physical feature is a long depression formed by earth movements?",
        choices: ["Rift valley", "Island", "Capital city", "Factory"],
        correct: 0,
        explanation: "A rift valley is a long depression formed by earth movements.",
      },
      writingTasks: [
        {
          title: "Case study: How physical features help people",
          prompt: "Choose one African physical feature and explain how it helps people and also creates challenges.",
          planningSteps: [
            "Name the physical feature and where it is found.",
            "Explain at least two benefits, such as fishing, farming, tourism, minerals or transport.",
            "Explain one challenge, such as flooding, steep slopes, disease vectors or transport difficulty.",
            "Suggest one way people can use the feature responsibly.",
          ],
          checklist: [
            "The feature is a real African physical feature.",
            "Benefits and challenges are both included.",
            "The answer links the feature to people's activities.",
            "Responsible use or conservation is mentioned.",
          ],
          modelOpening: "Lake Victoria is an important physical feature in East Africa. It supports fishing, transport and rainfall, but people must avoid polluting its water.",
        },
      ],
      recap: [
        "Physical features are natural features of the earth's surface.",
        "Africa has mountains, rivers, lakes, plateaus and rift valleys.",
        "Physical features influence settlement and economic activities.",
      ],
    },
    quiz: [
      { q: "Which is the highest mountain in Africa?", choices: ["Kilimanjaro", "Rwenzori", "Atlas", "Elgon"], correct: 0, why: "Mount Kilimanjaro in Tanzania is the highest mountain in Africa." },
      { q: "Which river is commonly known as the longest river in Africa?", choices: ["Nile", "Congo", "Niger", "Zambezi"], correct: 0, why: "The Nile is commonly taught as Africa's longest river." },
      { q: "A rift valley is formed mainly by:", choices: ["Earth movements", "Voting", "Fishing", "Factory smoke"], correct: 0, why: "Rift valleys form due to earth movements such as faulting." },
      { q: "Which lake is shared by Uganda, Kenya and Tanzania?", choices: ["Lake Victoria", "Lake Chad", "Lake Malawi", "Lake Turkana only"], correct: 0, why: "Lake Victoria is shared by Uganda, Kenya and Tanzania." },
      { q: "Which activity can be supported by waterfalls and fast-flowing rivers?", choices: ["Hydro-electric power generation", "Printing passports", "Making latitudes", "Forming parliaments"], correct: 0, why: "Fast-flowing water can turn turbines for hydro-electric power." },
      { q: "Which is a physical feature?", choices: ["River", "School uniform", "Parliament building", "Textbook"], correct: 0, why: "A river is a natural physical feature." },
      { q: "Which physical feature is a raised flat area?", choices: ["Plateau", "Valley only", "Ocean", "Capital city"], correct: 0, why: "A plateau is a raised area of land that is fairly flat on top." },
    ],
  },
  {
    id: "climate-of-africa",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Climate of Africa",
    estMinutes: 19,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Climate affects farming, settlement, vegetation, animals, transport and daily life. P7 learners need to know Africa's climatic regions and the factors that influence climate.",
      learningObjectives: [
        "Name major climatic regions of Africa.",
        "Describe characteristics of different climatic regions.",
        "Explain factors that influence climate in Africa.",
        "Show how climate affects human activities and how people affect climate.",
      ],
      whatYouNeedToKnow: [
        "Climate is the average weather condition of a place over a long period. Weather changes daily, but climate describes a longer pattern. Elements of weather and climate include rainfall, temperature, wind, humidity, sunshine, air pressure and cloud cover.",
        "Africa has climatic regions such as equatorial, tropical, desert, Mediterranean, semi-arid and mountain climate. Equatorial areas are generally hot and wet throughout the year, while desert areas are hot and dry with very little rainfall. Mediterranean areas have hot dry summers and cool wet winters.",
        "Factors that influence climate include latitude, altitude, distance from the sea, ocean currents, winds and relief. High places are cooler than low places, and places near the Equator are generally hotter. Windward slopes receive more rainfall than leeward slopes, which may be drier because of rain shadow.",
        "Climate influences farming, clothing, housing, settlement, transport and tourism. For example, wet areas support crop farming and forests, while dry areas may support pastoralism, irrigation farming or sparse settlement.",
        "Human activities such as deforestation, swamp drainage, bush burning, overgrazing, industrial pollution and settlement expansion can affect climate and rainfall patterns. Tree planting, wetland protection and careful land use help protect climate and the environment.",
      ],
      worked: {
        problem: "Why are highland areas often cooler than lowland areas near them?",
        steps: [
          "Step 1. Identify the factor: altitude or height above sea level.",
          "Step 2. Temperature decreases as altitude increases.",
          "Step 3. Therefore highlands are cooler than nearby lowlands.",
        ],
        answer: "Answer: Highland areas are cooler because temperature decreases as altitude increases.",
      },
      commonMistakes: [
        "Confusing weather and climate.",
        "Thinking all of Africa is desert.",
        "Forgetting altitude as a climate factor.",
        "Ignoring how human activities affect climate.",
      ],
      tryThis: {
        question: "Which climate is hot and dry with very little rainfall?",
        choices: ["Desert climate", "Equatorial climate", "Mountain climate", "Mediterranean climate"],
        correct: 0,
        explanation: "Desert climate has very little rainfall and is usually hot and dry.",
      },
      writingTasks: [
        {
          title: "Climate reasoning task: Farming and settlement",
          prompt: "Explain how climate affects farming and settlement in one region of Africa.",
          planningSteps: [
            "Name the climate region, such as equatorial, savanna, desert or Mediterranean.",
            "Describe rainfall and temperature in that region.",
            "Explain how the climate affects crops, animals or settlement patterns.",
            "Mention one human activity that can improve or damage the local climate/environment.",
          ],
          checklist: [
            "The climate type is named correctly.",
            "Rainfall and temperature are described.",
            "The link to farming or settlement is clear.",
            "Human influence on climate/environment is included.",
          ],
          modelOpening: "Savanna climate has wet and dry seasons. It supports grasslands, crop growing during the rainy season and pastoralism in some areas.",
        },
      ],
      recap: [
        "Climate is long-term average weather.",
        "Africa has several climatic regions.",
        "Latitude, altitude, winds, relief and distance from sea affect climate.",
        "Climate affects human activities and people can affect climate.",
      ],
    },
    quiz: [
      { q: "Climate means:", choices: ["Average weather over a long time", "Weather for one hour", "A capital city", "A mountain only"], correct: 0, why: "Climate is the average weather condition of a place over a long period." },
      { q: "Which factor explains why mountains are cooler?", choices: ["Altitude", "Population only", "Language", "Longitude only"], correct: 0, why: "Temperature decreases with increase in altitude." },
      { q: "Which climate has heavy rainfall and high temperatures throughout the year?", choices: ["Equatorial", "Desert", "Polar", "Mediterranean only"], correct: 0, why: "Equatorial climate is generally hot and wet throughout the year." },
      { q: "Which human activity can reduce rainfall over time?", choices: ["Deforestation", "Tree planting", "Soil conservation", "Agroforestry"], correct: 0, why: "Deforestation can reduce evapotranspiration and disturb rainfall patterns." },
      { q: "Which climate is found around parts of North Africa near the Mediterranean Sea?", choices: ["Mediterranean climate", "Polar climate", "Equatorial only", "Mountain only"], correct: 0, why: "Parts of North Africa near the Mediterranean Sea have Mediterranean climate." },
      { q: "Weather differs from climate because weather:", choices: ["Changes over a short time", "Never changes", "Means only rainfall", "Is a continent"], correct: 0, why: "Weather is the condition of the atmosphere over a short time." },
      { q: "Which activity is strongly influenced by climate?", choices: ["Farming", "Spelling only", "Drawing latitudes only", "Naming months only"], correct: 0, why: "Farmers depend on rainfall and temperature patterns." },
    ],
  },
  {
    id: "vegetation-of-africa",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Vegetation of Africa",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Vegetation affects animals, population distribution, farming, tourism and environmental protection across Africa.",
      learningObjectives: [
        "Name and locate major vegetation types of Africa.",
        "Explain factors that influence vegetation distribution.",
        "Describe the importance of vegetation and game parks.",
        "Relate vegetation to animals and population distribution.",
      ],
      whatYouNeedToKnow: [
        "Vegetation means the plant cover of an area. Africa's vegetation types include equatorial rainforest, savanna grassland, desert vegetation, Mediterranean vegetation, mountain vegetation, swamp vegetation and mangrove/coastal vegetation.",
        "Vegetation distribution is influenced by rainfall, temperature, altitude, soil, drainage, relief and human activities. Areas with heavy rainfall usually support thick forests, while dry areas have sparse vegetation. Mountain vegetation changes with height because temperature and rainfall change with altitude.",
        "Equatorial forests are dense and evergreen, savanna has grass with scattered trees, deserts have drought-resistant plants, Mediterranean vegetation has shrubs and trees adapted to dry summers, and mangroves grow in salty coastal/swampy areas.",
        "Vegetation is important because it provides food, timber, medicine, rainfall support, soil protection, animal habitats, grazing land, fuel, building materials and tourist attractions.",
        "Game parks protect wildlife and vegetation. Animals live in different vegetation zones because of food, water, shelter and climate conditions. For example, many grazing animals and predators live in savanna areas.",
        "Population distribution can be affected by vegetation. Very thick forests, deserts, tsetse-fly areas or disease-prone areas may have fewer people, while fertile grasslands may attract settlement and farming. Rapid population growth can lead to deforestation, overgrazing, bush burning and settlement expansion.",
      ],
      worked: {
        problem: "Why are savanna grasslands important to tourism in Africa?",
        steps: [
          "Step 1. Savanna has grass and scattered trees.",
          "Step 2. Many wild animals such as lions, elephants, giraffes and antelopes live there.",
          "Step 3. Tourists visit game parks to see these animals.",
        ],
        answer: "Answer: Savanna grasslands support wildlife, which attracts tourists to game parks.",
      },
      commonMistakes: [
        "Thinking vegetation means animals instead of plant cover.",
        "Saying all vegetation types support the same animals.",
        "Forgetting that people affect vegetation through farming, settlement and cutting trees.",
        "Ignoring the value of game parks.",
      ],
      tryThis: {
        question: "Which vegetation type has grass with scattered trees?",
        choices: ["Savanna", "Desert only", "Mangrove", "Ice cap"],
        correct: 0,
        explanation: "Savanna vegetation is mainly grass with scattered trees.",
      },
      writingTasks: [
        {
          title: "Vegetation comparison task",
          prompt: "Compare two vegetation zones of Africa and explain how each supports people or animals.",
          planningSteps: [
            "Choose two vegetation zones, such as equatorial forest and savanna.",
            "Describe the plants found in each zone.",
            "Explain how rainfall, temperature or altitude affects each zone.",
            "State how people or animals use each zone.",
          ],
          checklist: [
            "Two correct vegetation zones are compared.",
            "Characteristics of each zone are clear.",
            "Climate or relief influence is mentioned.",
            "Human/animal use is explained without encouraging destruction.",
          ],
          modelOpening: "Equatorial forests are thick and evergreen because they receive heavy rainfall, while savanna vegetation has grasses and scattered trees suited to wet and dry seasons.",
        },
      ],
      recap: [
        "Vegetation is plant cover.",
        "Rainfall and temperature strongly affect vegetation.",
        "Vegetation supports animals, people and tourism.",
        "Game parks protect wildlife and plant life.",
      ],
    },
    quiz: [
      { q: "Vegetation means:", choices: ["Plant cover of an area", "Capital city", "All rivers", "Only wild animals"], correct: 0, why: "Vegetation is the natural or planted plant cover of an area." },
      { q: "Which vegetation type is common in areas with heavy rainfall near the Equator?", choices: ["Equatorial rainforest", "Desert vegetation", "Mediterranean scrub only", "Tundra"], correct: 0, why: "Heavy rainfall near the Equator supports equatorial rainforest." },
      { q: "Which factor strongly influences vegetation distribution?", choices: ["Rainfall", "Flag colour", "Capital name", "Number plate"], correct: 0, why: "Rainfall affects the type and amount of vegetation in an area." },
      { q: "Game parks are important because they:", choices: ["Protect wildlife", "Destroy all forests", "Stop tourism", "Remove all animals"], correct: 0, why: "Game parks protect animals and their habitats." },
      { q: "Which animal is commonly associated with savanna grassland?", choices: ["Lion", "Polar bear", "Penguin", "Whale only"], correct: 0, why: "Lions live in savanna ecosystems where prey animals are found." },
      { q: "Which activity can destroy vegetation?", choices: ["Bush burning", "Tree planting", "Controlled grazing", "Protecting seedlings"], correct: 0, why: "Bush burning can destroy plant cover and animal habitats." },
      { q: "Why may deserts have low population density?", choices: ["Little water and sparse vegetation", "Too many schools", "Too much rainfall", "Too many lakes"], correct: 0, why: "Deserts have little water and sparse vegetation, making settlement difficult." },
    ],
  },
  {
    id: "people-ethnic-groups-settlement",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "People of Africa, ethnic groups and settlement patterns",
    estMinutes: 17,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: African societies have different origins, migrations, languages and settlement patterns. The topic helps learners appreciate unity in diversity.",
      learningObjectives: [
        "Describe origins and movements of different ethnic groups in Africa.",
        "Identify settlement patterns of ethnic groups.",
        "Give reasons for migration and settlement.",
        "Explain problems and effects of ethnic migrations.",
      ],
      whatYouNeedToKnow: [
        "An ethnic group is a group of people who share common culture, language, origin or history. Africa has many ethnic groups, including Bantu, Nilotes, Cushites, Semites, Berbers and others.",
        "Migration is the movement of people from one place to another. People migrated because of population increase, search for land and water, wars, internal conflicts, trade, harsh climate, diseases and expansion of kingdoms.",
        "During migration, people faced problems such as resistance from indigenous people, wild animals, diseases, difficult terrain, food shortage, water shortage and harsh climate.",
        "Migrations changed population distribution, spread cultures and languages, caused intermarriages, led to conflicts in some areas and helped form new settlements.",
        "Settlement patterns are influenced by relief, climate, water, vegetation, security, fertile soils and economic activities.",
      ],
      worked: {
        problem: "Give three reasons why ethnic groups migrated in Africa.",
        steps: [
          "Step 1. Think about needs: people need land, water and food.",
          "Step 2. Think about danger: wars and conflicts can force people to move.",
          "Step 3. Think about environment: harsh climate or disease can push people away.",
        ],
        answer: "Answer: Ethnic groups migrated because of search for land and water, wars or conflicts, and harsh climate or disease.",
      },
      commonMistakes: [
        "Using tribe and ethnic group carelessly as if they always mean exactly the same thing.",
        "Thinking migration had only one cause.",
        "Forgetting both positive and negative effects of migration.",
        "Ignoring unity and respect among different cultures.",
      ],
      tryThis: {
        question: "What is migration?",
        choices: ["Movement of people from one place to another", "A type of mountain", "A capital city", "A climate zone only"],
        correct: 0,
        explanation: "Migration is movement from one place to another.",
      },
      writingTasks: [
        {
          title: "Migration task: Push and pull factors",
          prompt: "Explain why people move from one place to another and how migration can affect settlement patterns.",
          planningSteps: [
            "Define migration in simple words.",
            "Give two push factors that force people to leave a place.",
            "Give two pull factors that attract people to a new place.",
            "Explain one effect of migration on settlement or culture.",
          ],
          checklist: [
            "Push and pull factors are separated correctly.",
            "Examples are realistic for Africa.",
            "Settlement pattern is mentioned.",
            "Different ethnic groups are discussed respectfully.",
          ],
          modelOpening: "Migration is the movement of people from one place to another. People may leave an area because of drought or conflict and move to places with fertile land, water or jobs.",
        },
      ],
      recap: [
        "Africa has many ethnic groups.",
        "Migration has push and pull reasons.",
        "People faced challenges during movement and settlement.",
        "Learners should appreciate unity in diversity.",
      ],
    },
    quiz: [
      { q: "An ethnic group commonly shares:", choices: ["Culture and origin", "Only shoe size", "Only rainfall", "Only road signs"], correct: 0, why: "Ethnic groups often share culture, language, origin or history." },
      { q: "Migration means:", choices: ["Movement of people from one place to another", "Growth of grass", "Building a dam", "Drawing a map only"], correct: 0, why: "Migration is the movement of people from one place to another." },
      { q: "Which is a reason for migration?", choices: ["Search for land", "Too many latitudes", "A mirror image", "Short circuit"], correct: 0, why: "People may migrate to find land for settlement and farming." },
      { q: "Which problem could migrants meet?", choices: ["Food and water shortage", "Too much homework only", "Plane mirror", "A fuse"], correct: 0, why: "Migrants could face shortages of food and water during movement." },
      { q: "Which is an effect of migration?", choices: ["Spread of cultures", "Stopping all languages", "Removing all rivers", "Ending all settlement"], correct: 0, why: "Migration can spread cultures, languages and practices." },
      { q: "Which factor affects settlement patterns?", choices: ["Water supply", "Book colour", "Answer letter", "Bell sound only"], correct: 0, why: "People often settle near reliable water sources." },
      { q: "Why should learners study ethnic groups respectfully?", choices: ["To appreciate unity in diversity", "To insult other cultures", "To create conflict", "To hide history"], correct: 0, why: "Social Studies encourages respect for different cultures and unity in diversity." },
    ],
  },
  {
    id: "foreign-influence-africa",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Foreign influence in Africa",
    estMinutes: 20,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Foreign traders, explorers, missionaries, colonialists and settlers affected Africa politically, economically and socially. P7 learners need to understand causes, methods and effects.",
      learningObjectives: [
        "Identify foreign groups that came to Africa.",
        "Explain reasons for the coming of explorers, traders, missionaries and colonialists.",
        "Describe the scramble and partition of Africa.",
        "Explain effects of foreign influence and methods of colonial rule.",
      ],
      whatYouNeedToKnow: [
        "Foreign groups that came to Africa included Arab traders, Persian and Indian traders, European explorers, missionaries, traders, colonialists and settlers. They did not all come at the same time or for the same reason.",
        "Explorers came for curiosity, fame, mapping, search for trade routes, sources of rivers and information about Africa. Examples often studied include David Livingstone, Mungo Park, Bartholomew Diaz and the Landers. Explorers faced diseases, wild animals, difficult terrain, language barriers and resistance.",
        "Traders came for goods such as gold, ivory, spices and later raw materials and markets. The Trans-Atlantic/Triangular trade connected Europe, Africa and the Americas and caused great suffering through slave trade and exploitation.",
        "Missionaries came to spread Christianity, build schools and hospitals, translate religious materials and campaign against some practices such as slave trade. Their work also prepared the way for deeper European influence in some places.",
        "Colonialists came to control land, labour, raw materials, markets and strategic areas. The scramble and partition of Africa refers to European powers rushing to claim and divide African territories, especially after the Berlin Conference of 1884–1885.",
        "Colonial rule was established through treaties, force, divide and rule, company rule and taking advantage of existing conflicts. Colonies were administered using methods such as direct rule, indirect rule and assimilation.",
        "Foreign influence had political effects such as loss of independence, economic effects such as exploitation and infrastructure development, and social effects such as formal education, religion, new languages, intermarriages and cultural change. Africans reacted through cooperation, resistance, protest and later nationalism.",
      ],
      worked: {
        problem: "Give one political, one economic and one social effect of foreign influence in Africa.",
        steps: [
          "Step 1. Political: Africans lost independence in many places.",
          "Step 2. Economic: raw materials were exploited, but roads and railways were also built.",
          "Step 3. Social: Christianity, Islam in some areas, formal education and foreign languages spread.",
        ],
        answer: "Answer: Political — loss of independence. Economic — exploitation of raw materials. Social — formal education and foreign languages spread.",
      },
      commonMistakes: [
        "Thinking all foreigners came for the same reason.",
        "Forgetting the difference between explorers, missionaries, traders and colonialists.",
        "Listing only positive or only negative effects.",
        "Confusing direct rule, indirect rule and assimilation.",
      ],
      tryThis: {
        question: "What was the scramble for Africa?",
        choices: ["European rush to claim African territories", "A football game", "A climate region", "A type of vegetation"],
        correct: 0,
        explanation: "The scramble for Africa was the European rush to claim and control African territories.",
      },
      writingTasks: [
        {
          title: "History source task: Foreign groups in Africa",
          prompt: "Explain how one foreign group influenced Africa and give both positive and negative effects where appropriate.",
          planningSteps: [
            "Choose one group: traders, explorers, missionaries, colonialists or settlers.",
            "State why they came to Africa.",
            "Explain at least two effects of their coming.",
            "Separate facts from opinions and avoid one-sided answers.",
          ],
          checklist: [
            "The chosen foreign group is clearly named.",
            "Reasons for coming are correct.",
            "Effects are specific and balanced.",
            "Historical terms such as colonialism, trade or missionary work are used correctly.",
          ],
          modelOpening: "Missionaries came to Africa mainly to spread Christianity. They built schools and hospitals, but their coming also helped prepare the way for colonial influence in some areas.",
        },
      ],
      recap: [
        "Different foreign groups came to Africa for different reasons.",
        "Colonialism led to loss of independence.",
        "Foreign influence had political, economic and social effects.",
        "Africans reacted to colonial rule in different ways.",
      ],
    },
    quiz: [
      { q: "Which group came mainly to spread Christianity?", choices: ["Missionaries", "Only miners", "Only soldiers", "Only farmers"], correct: 0, why: "Missionaries came mainly to spread Christianity and build mission stations." },
      { q: "The scramble for Africa means:", choices: ["European rush to claim African territories", "African football tournament", "Formation of rainfall", "A type of map scale"], correct: 0, why: "The scramble for Africa was the rush by European powers to claim African territories." },
      { q: "Which was a political effect of colonial rule?", choices: ["Loss of independence", "Formation of clouds", "Growth of savanna", "Making longitudes"], correct: 0, why: "Colonised African societies lost political independence." },
      { q: "Which was an economic reason for colonialism?", choices: ["Search for raw materials and markets", "Correction of eyesight", "Formation of rift valleys", "Migration of birds only"], correct: 0, why: "European powers wanted raw materials, markets and wealth." },
      { q: "Which method was used to administer colonies?", choices: ["Indirect rule", "Latitude rule", "Vegetation rule", "Weather rule"], correct: 0, why: "Indirect rule was one method used by colonial administrators." },
      { q: "The Great Trek is associated with which country?", choices: ["South Africa", "Uganda only", "Libya only", "Mali only"], correct: 0, why: "The Great Trek was a major movement of Boers in South Africa." },
      { q: "Which is a social effect of foreign influence?", choices: ["Formal schooling spread", "All rivers dried", "Mountains disappeared", "All climates ended"], correct: 0, why: "Foreign influence contributed to the spread of formal schooling." },
    ],
  },
  {
    id: "nationalism-road-independence",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Nationalism and the road to independence of Africa",
    estMinutes: 20,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Learners need to understand how African people organised to regain independence and why patriotism, nationalism and Pan-Africanism mattered.",
      learningObjectives: [
        "Explain nationalism, patriotism and Pan-Africanism.",
        "Identify leading Pan-Africanists and nationalists.",
        "Describe methods used to fight for independence.",
        "Compare single-party and multiparty systems.",
      ],
      whatYouNeedToKnow: [
        "Nationalism is love for and loyalty to one's nation, often shown through the desire for self-rule. A nationalist is a person who works for the interests or independence of a nation. Patriotism is love for one's country and willingness to serve it responsibly.",
        "Pan-Africanism is the idea that African people should unite, support one another and work for freedom and development. Pan-Africanists encouraged African pride, unity and resistance to colonial domination.",
        "Pan-Africanists and nationalists used political parties, newspapers, petitions, strikes, boycotts, demonstrations, negotiations, armed struggle in some places and international pressure to demand independence.",
        "Leading African nationalists and Pan-Africanists included people such as Kwame Nkrumah, Jomo Kenyatta, Julius Nyerere, Patrice Lumumba, Nelson Mandela and others. Learners should connect leaders with the wider struggle for self-rule, not memorise names only.",
        "Ethiopia and Liberia are commonly studied as African countries that were not colonised in the same way as most African states. Ethiopia resisted Italian invasion, while Liberia had a special history linked to freed formerly enslaved people from America.",
        "Nationalists faced problems such as arrest, imprisonment, exile, censorship, lack of funds, tribal or religious divisions, poor communication and strong colonial armies.",
        "Multiparty systems allow more than one political party to compete for power. Single-party systems allow one legal ruling party. Each system has claimed advantages and disadvantages, but democratic participation, accountability, peaceful transfer of power and respect for rights are important.",
      ],
      worked: {
        problem: "Differentiate nationalism and Pan-Africanism.",
        steps: [
          "Step 1. Nationalism focuses on love for and self-rule of a nation.",
          "Step 2. Pan-Africanism focuses on unity and cooperation of African people.",
          "Step 3. Both helped the struggle for independence.",
        ],
        answer: "Answer: Nationalism is loyalty to one's nation and desire for self-rule; Pan-Africanism is the unity and cooperation of African people.",
      },
      commonMistakes: [
        "Confusing patriotism with Pan-Africanism.",
        "Thinking independence came by only one method everywhere.",
        "Forgetting problems faced by nationalists, such as imprisonment and limited funds.",
        "Assuming every African country followed the same path to independence.",
      ],
      tryThis: {
        question: "Which idea encouraged African people to unite for freedom and development?",
        choices: ["Pan-Africanism", "Desertification", "Assimilation only", "Latitude"],
        correct: 0,
        explanation: "Pan-Africanism promotes unity and cooperation among African people.",
      },
      writingTasks: [
        {
          title: "Nationalist profile task",
          prompt: "Choose one African nationalist and explain how he or she contributed to the struggle for independence.",
          planningSteps: [
            "Name the nationalist and country.",
            "State the colonial power or problem being opposed.",
            "Describe methods used, such as parties, writing, protests, negotiation or armed struggle.",
            "Mention one challenge faced by nationalists.",
          ],
          checklist: [
            "The nationalist and country are correct.",
            "Methods of struggle are explained.",
            "The answer uses terms like nationalism, independence or self-rule correctly.",
            "Challenges are included.",
          ],
          modelOpening: "Kwame Nkrumah was a nationalist leader in Ghana. He helped organise people through political action and demanded self-rule from British colonial rule.",
        },
      ],
      recap: [
        "Nationalism helped African countries demand self-rule.",
        "Pan-Africanism promoted African unity.",
        "Nationalists used peaceful and sometimes armed methods.",
        "Political systems affect participation and accountability.",
      ],
    },
    quiz: [
      { q: "Nationalism means:", choices: ["Love for and loyalty to one's nation", "A type of lake", "A climate zone", "A vegetation belt"], correct: 0, why: "Nationalism is love for and loyalty to one's nation, often linked to self-rule." },
      { q: "Pan-Africanism promotes:", choices: ["African unity", "Colonial rule", "Desert expansion", "River flooding only"], correct: 0, why: "Pan-Africanism promotes unity and cooperation among African people." },
      { q: "Which country is commonly studied as having resisted colonisation by Italy?", choices: ["Ethiopia", "Kenya", "Ghana", "Nigeria"], correct: 0, why: "Ethiopia is known for resisting Italian colonisation, especially at Adwa." },
      { q: "Which method was used by nationalists?", choices: ["Forming political parties", "Creating deserts", "Stopping all schools", "Making oceans"], correct: 0, why: "Political parties helped mobilise people for independence." },
      { q: "A multiparty system means:", choices: ["More than one political party can compete", "Only one river exists", "No voting is allowed", "All countries have one capital"], correct: 0, why: "Multiparty systems allow more than one party to compete for power." },
      { q: "Which problem did nationalists often face?", choices: ["Imprisonment", "Too many oceans", "No mountains in Africa", "Lack of sunlight everywhere"], correct: 0, why: "Many nationalists were arrested or imprisoned by colonial governments." },
      { q: "Patriotism means:", choices: ["Love for one's country", "Fear of maps", "A type of rainfall", "A lake"], correct: 0, why: "Patriotism is love for and commitment to one's country." },
    ],
  },
  {
    id: "post-independence-africa",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Post-independence Africa",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: After independence, African countries formed organisations to promote unity, peace, development and cooperation. Learners need to know OAU, AU and regional economic groupings.",
      learningObjectives: [
        "Explain why the OAU was formed and what it achieved.",
        "Describe the formation and objectives of the AU.",
        "Name major regional economic groupings in Africa.",
        "Explain advantages, challenges and solutions for cooperation.",
      ],
      whatYouNeedToKnow: [
        "The Organisation of African Unity (OAU) was formed in 1963 in Addis Ababa, Ethiopia. It aimed to promote African unity, support liberation movements, defend sovereignty and encourage cooperation.",
        "The African Union (AU) replaced the OAU in 2002. The AU aims to promote unity, peace, democracy, development, human rights and cooperation among African states.",
        "Regional economic groupings include COMESA, ECOWAS, SADC and IGAD. They encourage trade, transport links, peace efforts and economic cooperation among member states.",
        "Advantages of cooperation include larger markets, peace-building, shared infrastructure, easier trade and stronger bargaining power. Challenges include conflicts, poor transport, political differences, poverty and unequal development.",
      ],
      worked: {
        problem: "Give two advantages of regional economic cooperation in Africa.",
        steps: [
          "Step 1. Think about trade: countries can sell goods to a bigger market.",
          "Step 2. Think about infrastructure: countries can work together on roads, railways and energy.",
          "Step 3. State the points clearly.",
        ],
        answer: "Answer: It creates larger markets for goods and encourages shared infrastructure development.",
      },
      commonMistakes: [
        "Confusing OAU and AU dates.",
        "Thinking all regional groupings cover the whole of Africa.",
        "Forgetting both advantages and challenges of cooperation.",
        "Writing abbreviations without knowing their meaning.",
      ],
      tryThis: {
        question: "Which organisation replaced the OAU?",
        choices: ["African Union", "United Nations", "COMESA only", "Commonwealth"],
        correct: 0,
        explanation: "The African Union replaced the Organisation of African Unity.",
      },
      writingTasks: [
        {
          title: "Problem-solution task: Post-independence Africa",
          prompt: "Choose one problem faced by African countries after independence and suggest practical solutions.",
          planningSteps: [
            "Name the problem, such as political instability, poverty, corruption, disease or poor transport.",
            "Explain why the problem affected development.",
            "Give two possible solutions.",
            "Mention the role of citizens, leaders or regional organisations.",
          ],
          checklist: [
            "The problem is clearly linked to post-independence Africa.",
            "Effects on development are explained.",
            "Solutions are realistic.",
            "The answer promotes responsible citizenship and leadership.",
          ],
          modelOpening: "One problem faced by some African countries after independence was political instability. It reduced peace, slowed development and discouraged investment.",
        },
      ],
      recap: [
        "OAU promoted African unity and liberation.",
        "AU continues cooperation with wider development and governance aims.",
        "COMESA, ECOWAS, SADC and IGAD are regional groupings.",
        "Cooperation has benefits and challenges.",
      ],
    },
    quiz: [
      { q: "The OAU was formed in:", choices: ["1963", "2002", "1884", "1995"], correct: 0, why: "The OAU was formed in 1963." },
      { q: "Which organisation replaced the OAU?", choices: ["AU", "UNICEF", "WHO", "NATO"], correct: 0, why: "The African Union replaced the Organisation of African Unity." },
      { q: "COMESA is an example of:", choices: ["Regional economic grouping", "Mountain range", "Desert", "Lake"], correct: 0, why: "COMESA is a regional economic grouping." },
      { q: "Which is an advantage of economic cooperation?", choices: ["Larger markets", "More isolation", "Stopping all trade", "Removing roads"], correct: 0, why: "Cooperation gives countries access to larger markets." },
      { q: "Which challenge can affect African cooperation?", choices: ["Political conflicts", "Too many equators", "No countries", "No resources anywhere"], correct: 0, why: "Conflicts between or within states can weaken cooperation." },
      { q: "IGAD is mainly associated with which region?", choices: ["Eastern/Horn of Africa", "South America", "Europe", "Australia"], correct: 0, why: "IGAD groups countries in Eastern Africa and the Horn of Africa." },
      { q: "One aim of the AU is to promote:", choices: ["Peace and development", "Colonial rule", "Slave trade", "Desert expansion only"], correct: 0, why: "The AU aims to promote peace, unity and development." },
    ],
  },
  {
    id: "economic-developments-africa",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Economic developments in Africa",
    estMinutes: 22,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: Africa's resources and economic activities shape development. P7 learners compare case studies such as Nigeria, Sudan, Libya, South Africa, DRC and Uganda.",
      learningObjectives: [
        "Name major economic resources of Africa.",
        "Explain problems faced in using resources.",
        "Describe case studies of economic development in selected countries.",
        "Suggest solutions to challenges affecting development in Africa.",
      ],
      whatYouNeedToKnow: [
        "Major economic resources of Africa include minerals, oil, fertile soils, forests, water, wildlife, fisheries, sunshine, wind and human labour. Resources only support development when they are managed well.",
        "Economic activities include farming, mining, tourism, trade, transport, fishing, pastoralism, irrigation, hydro-electric power generation and industrialisation. These activities create jobs, income, taxes, exports and services when organised properly.",
        "Case studies include Nigeria's oil and farming, Sudan's Gezira Irrigation Scheme and Nile Valley, Libya's oil and irrigation, South Africa's mining and industry, DRC's minerals and forests, and Uganda's farming, tourism, mining, irrigation and pastoralism.",
        "Nigeria is known for oil, farming, trade and transport. Sudan is studied for the Nile Valley, Gezira irrigation and hydro-electric power. Libya is known for oil, desert irrigation, tourism and industrialisation. South Africa is known for mining, farming, industry, trade and tourism. DRC is rich in minerals, forests, water power and wildlife. Uganda is known for farming, tourism, mining, fisheries, irrigation and pastoralism.",
        "Problems affecting resource use include poor transport, limited capital, low technology, political instability, corruption, poor markets, climate problems, land conflicts, low value addition and environmental degradation.",
        "Solutions include good governance, peace, better roads and railways, value addition, skilled labour, environmental care, regional trade, fair markets, investment in energy, and responsible use of resources.",
      ],
      worked: {
        problem: "Why is value addition important for African resources?",
        steps: [
          "Step 1. Raw materials are often sold cheaply.",
          "Step 2. Processing them into finished or semi-finished goods increases their value.",
          "Step 3. This can create jobs and more income.",
        ],
        answer: "Answer: Value addition increases income from resources and creates jobs by processing raw materials before sale.",
      },
      commonMistakes: [
        "Listing resources without explaining their economic use.",
        "Thinking resource wealth automatically means development.",
        "Forgetting environmental care when using resources.",
        "Mixing up country case studies.",
      ],
      tryThis: {
        question: "Which country is well known for oil production in West Africa?",
        choices: ["Nigeria", "Uganda", "Kenya", "Rwanda"],
        correct: 0,
        explanation: "Nigeria is a major oil producer in West Africa.",
      },
      writingTasks: [
        {
          title: "Country case study: Resources and development",
          prompt: "Choose one African country and explain how its resources can support economic development.",
          planningSteps: [
            "Name the country and at least two resources or economic activities.",
            "Explain how the resources create jobs, trade or income.",
            "Mention one problem that can limit development.",
            "Suggest one way to improve resource use responsibly.",
          ],
          checklist: [
            "Country examples are accurate.",
            "Resources are linked to economic activities.",
            "Problems such as poor transport, conflict or low value addition are mentioned.",
            "Responsible development and environmental care are included.",
          ],
          modelOpening: "Nigeria has petroleum, fertile land and a large population. Petroleum can earn foreign exchange, while farming and industries can create jobs when resources are managed well.",
        },
      ],
      recap: [
        "Africa has many natural and human resources.",
        "Economic development depends on how resources are used.",
        "Case studies help compare countries.",
        "Peace, skills, infrastructure and good governance support development.",
      ],
    },
    quiz: [
      { q: "Which is a major economic resource in Nigeria?", choices: ["Oil", "Snowfields", "Polar bears", "Volcanoes only"], correct: 0, why: "Nigeria is well known for oil production." },
      { q: "The Gezira Irrigation Scheme is associated with:", choices: ["Sudan", "South Africa", "Ghana", "Morocco only"], correct: 0, why: "The Gezira Scheme is a major irrigation project in Sudan." },
      { q: "Which country is known for strong mining and industrial development in Southern Africa?", choices: ["South Africa", "Chad", "Somalia", "Rwanda only"], correct: 0, why: "South Africa is known for mining and industrial development." },
      { q: "Which problem can limit economic development?", choices: ["Poor transport", "Good roads", "Skilled labour", "Peace"], correct: 0, why: "Poor transport makes movement of goods and people difficult." },
      { q: "Value addition means:", choices: ["Processing raw materials to increase value", "Wasting resources", "Stopping trade", "Cutting all forests"], correct: 0, why: "Value addition increases the worth of raw materials by processing them." },
      { q: "Which activity is important for Uganda's economy?", choices: ["Farming", "Polar fishing", "Ice mining", "Penguin tourism"], correct: 0, why: "Farming is a major economic activity in Uganda." },
      { q: "Which solution can support development?", choices: ["Good governance", "Corruption", "Civil war", "Destroying roads"], correct: 0, why: "Good governance supports planning, investment and fair use of resources." },
    ],
  },
  {
    id: "major-world-organisations",
    themeId: "sst-living-together-africa",
    themeName: "Living Together in Africa",
    title: "Major world organisations",
    estMinutes: 18,
    status: "published",
    reviewStatus: "verified",
    note: {
      intro: "Why this matters: African countries relate with global organisations such as the United Nations and the Commonwealth. Learners need to know their origin, aims, organs, agencies, functions and challenges.",
      learningObjectives: [
        "Explain the origin, objectives and organs of the United Nations.",
        "Name UN agencies and their functions.",
        "Describe the UN Human Rights Charter in simple terms.",
        "Explain membership, functions and challenges of the Commonwealth of Nations.",
      ],
      whatYouNeedToKnow: [
        "The United Nations (UN) was formed in 1945 after the Second World War to promote peace, security, cooperation, human rights and development among nations. Its headquarters are in New York, USA.",
        "Important organs of the UN include the General Assembly, Security Council, International Court of Justice, Secretariat and Economic and Social Council. The General Assembly gives all member states a voice, while the Security Council has special responsibility for peace and security.",
        "UN agencies include UNICEF for children, WHO for health, FAO for food and agriculture, UNESCO for education, science and culture, UNHCR for refugees and WFP for food assistance. Learners should match each agency to its work, not memorise abbreviations only.",
        "Human rights are basic freedoms and protections every person should enjoy, such as the right to life, education, health, fair treatment, worship, expression and freedom from discrimination. Rights go together with responsibilities.",
        "The Commonwealth is an association of countries, many of which were formerly linked to Britain. It promotes cooperation, democracy, education, trade, sports, scholarships and shared values.",
        "Challenges faced by international organisations include limited funds, conflicts, powerful countries' interests, slow decision-making, veto power disagreements, refugee crises, climate disasters and failure by members to respect agreements.",
      ],
      worked: {
        problem: "Match two UN agencies with their work: UNICEF and WHO.",
        steps: [
          "Step 1. UNICEF focuses on children and their welfare.",
          "Step 2. WHO focuses on health and disease control.",
          "Step 3. Write the matches clearly.",
        ],
        answer: "Answer: UNICEF supports children; WHO promotes health and fights diseases.",
      },
      commonMistakes: [
        "Confusing UN organs and UN agencies.",
        "Thinking the Commonwealth and United Nations are the same organisation.",
        "Forgetting that the UN was formed after World War II.",
        "Writing agency abbreviations without knowing their work.",
      ],
      tryThis: {
        question: "Which UN agency is mainly concerned with health?",
        choices: ["WHO", "UNICEF", "FAO", "UNESCO"],
        correct: 0,
        explanation: "WHO stands for World Health Organization and focuses on health.",
      },
      writingTasks: [
        {
          title: "Organisation matching task",
          prompt: "Choose one major world organisation and explain its work in Africa.",
          planningSteps: [
            "Name the organisation, such as UN, AU, Commonwealth or an agency like WHO/UNICEF.",
            "State its main purpose.",
            "Give two examples of how it helps people or countries.",
            "Mention one challenge the organisation may face.",
          ],
          checklist: [
            "The organisation and its purpose are correct.",
            "Examples match the organisation's work.",
            "Challenges are realistic.",
            "The answer connects rights, peace, health, education or cooperation where relevant.",
          ],
          modelOpening: "The United Nations promotes peace, cooperation and human rights. In Africa, its agencies may support refugees, health, education and emergency relief.",
        },
      ],
      recap: [
        "The UN was formed in 1945 to promote peace and cooperation.",
        "UN agencies handle children, health, food, education, refugees and other needs.",
        "The Commonwealth links member countries for cooperation.",
        "World organisations face funding, conflict and decision-making challenges.",
      ],
    },
    quiz: [
      { q: "The United Nations was formed in:", choices: ["1945", "1963", "2002", "1884"], correct: 0, why: "The UN was formed in 1945 after World War II." },
      { q: "Which UN agency focuses mainly on children?", choices: ["UNICEF", "WHO", "FAO", "WFP"], correct: 0, why: "UNICEF supports children's welfare and rights." },
      { q: "Which UN agency focuses on health?", choices: ["WHO", "UNESCO", "UNHCR", "FAO"], correct: 0, why: "WHO is the World Health Organization." },
      { q: "Which organ of the UN helps maintain international peace and security?", choices: ["Security Council", "Sports Council", "School Council", "Vegetation Council"], correct: 0, why: "The Security Council has a major role in international peace and security." },
      { q: "The Commonwealth is mainly an association of:", choices: ["Member countries cooperating together", "Only rivers", "Only deserts", "Only mountains"], correct: 0, why: "The Commonwealth is an association of member countries." },
      { q: "Which is a human right?", choices: ["Right to education", "Right to steal", "Right to pollute", "Right to violence"], correct: 0, why: "Education is recognised as a basic human right." },
      { q: "Which challenge can affect the UN?", choices: ["Limited funds", "Too many equators", "No countries in the world", "No need for peace"], correct: 0, why: "Limited funds can make it hard for the UN to carry out its work." },
    ],
  },
];

export function getSocialTopic(id: string): Topic | undefined {
  return SOCIAL_TOPICS.find((topic) => topic.id === id);
}
