"use client";

import { useMemo, useState } from "react";
import { listBankTopics, sampleAcrossTopics, type BankQuestion } from "@/lib/question-bank";

const LETTERS = ["A", "B", "C", "D"] as const;

type Difficulty = "all" | "easy" | "medium" | "hard";

interface SampledQ extends BankQuestion {
  topicId: string;
  topicTitle: string;
}

export default function WorksheetGenerator() {
  const topics = useMemo(() => listBankTopics(), []);
  const [selected, setSelected] = useState<Set<string>>(() => new Set(topics.map((t) => t.topicId)));
  const [count, setCount] = useState(15);
  const [difficulty, setDifficulty] = useState<Difficulty>("all");
  const [showAnswers, setShowAnswers] = useState(true);
  const [worksheet, setWorksheet] = useState<SampledQ[] | null>(null);
  const [title, setTitle] = useState("P7 Mathematics worksheet");
  const [schoolName, setSchoolName] = useState("");

  function toggle(id: string) {
    setSelected((s) => {
      const next = new Set(s);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function selectAll() { setSelected(new Set(topics.map((t) => t.topicId))); }
  function selectNone() { setSelected(new Set()); }

  function generate() {
    const ids = Array.from(selected);
    if (ids.length === 0) {
      alert("Please select at least one topic.");
      return;
    }
    let pool = sampleAcrossTopics(ids, count * 3); // oversample so difficulty filter has room
    if (difficulty !== "all") {
      pool = pool.filter((q) => q.difficulty === difficulty);
    }
    if (pool.length === 0) {
      alert("No questions match those filters. Try widening the selection or difficulty.");
      return;
    }
    setWorksheet(pool.slice(0, count));
  }

  function copyAsText() {
    if (!worksheet) return;
    const lines: string[] = [];
    if (schoolName.trim()) lines.push(schoolName.trim().toUpperCase());
    lines.push(title.toUpperCase());
    lines.push("Generated by Tendo · " + new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }));
    lines.push(`Name: ____________________________   Class: __________   Date: __________`);
    lines.push("");
    lines.push(`Instructions: Answer all ${worksheet.length} questions. Circle the correct option.`);
    lines.push("");
    worksheet.forEach((q, i) => {
      lines.push(`${i + 1}. (${q.topicTitle}) ${q.q}`);
      q.choices.forEach((c, j) => lines.push(`     ${LETTERS[j]}) ${c}`));
      if (showAnswers) {
        lines.push(`     ANSWER: ${LETTERS[q.correct]} — ${q.why}`);
      }
      lines.push("");
    });
    const text = lines.join("\n");
    try {
      navigator.clipboard.writeText(text);
      alert("Worksheet copied. Paste into Word, WhatsApp, or your email.");
    } catch {
      const w = window.open();
      if (w) w.document.write(`<pre>${text.replace(/</g, "&lt;")}</pre>`);
    }
  }

  function printWorksheet() {
    window.print();
  }

  return (
    <>
      {!worksheet && (
        <div className="generator-form no-print">
          <h2>1. Title</h2>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Worksheet title"
            className="text-input"
          />
          <input
            type="text"
            value={schoolName}
            onChange={(e) => setSchoolName(e.target.value)}
            placeholder="School name (optional)"
            className="text-input"
            style={{ marginTop: 8 }}
          />

          <h2>2. Topics</h2>
          <div className="generator-toolbar">
            <button type="button" className="link-btn" onClick={selectAll}>Select all</button>
            <button type="button" className="link-btn" onClick={selectNone}>Select none</button>
            <span className="generator-count">{selected.size} of {topics.length} topics</span>
          </div>
          <div className="topic-chips">
            {topics.map((t) => {
              const on = selected.has(t.topicId);
              return (
                <button
                  type="button"
                  key={t.topicId}
                  className={"topic-chip" + (on ? " on" : "")}
                  onClick={() => toggle(t.topicId)}
                >
                  {t.topicTitle}
                  <span className="topic-chip-count">{t.count}</span>
                </button>
              );
            })}
          </div>

          <h2>3. Length and difficulty</h2>
          <div className="generator-controls">
            <label className="ctl">
              <span>Number of questions</span>
              <input
                type="number"
                min={1}
                max={50}
                value={count}
                onChange={(e) => setCount(Math.max(1, Math.min(50, Number(e.target.value) || 1)))}
                className="num-input"
              />
            </label>
            <label className="ctl">
              <span>Difficulty</span>
              <select value={difficulty} onChange={(e) => setDifficulty(e.target.value as Difficulty)} className="num-input">
                <option value="all">Mixed</option>
                <option value="easy">Easy only</option>
                <option value="medium">Medium only</option>
                <option value="hard">Hard only</option>
              </select>
            </label>
            <label className="ctl">
              <span>Answer key</span>
              <select
                value={showAnswers ? "yes" : "no"}
                onChange={(e) => setShowAnswers(e.target.value === "yes")}
                className="num-input"
              >
                <option value="yes">Include with answers</option>
                <option value="no">Questions only</option>
              </select>
            </label>
          </div>

          <div style={{ marginTop: 24 }}>
            <button className="btn btn-primary btn-block" onClick={generate}>
              Generate worksheet
            </button>
          </div>
        </div>
      )}

      {worksheet && (
        <>
          <div className="generator-toolbar no-print" style={{ marginBottom: 24 }}>
            <button className="btn btn-secondary" onClick={() => setWorksheet(null)}>
              ← Edit settings
            </button>
            <button className="btn btn-secondary" onClick={generate}>
              Shuffle again
            </button>
            <label className="toggle" style={{ marginLeft: "auto" }}>
              <input type="checkbox" checked={showAnswers} onChange={(e) => setShowAnswers(e.target.checked)} />
              Show answers
            </label>
            <button className="btn btn-secondary" onClick={copyAsText}>Copy as text</button>
            <button className="btn btn-primary" onClick={printWorksheet}>Print</button>
          </div>

          <div className="worksheet">
            {schoolName.trim() && <h2 className="worksheet-school">{schoolName.trim().toUpperCase()}</h2>}
            <h1 className="worksheet-title">{title}</h1>
            <div className="worksheet-meta">
              Name: __________________________ &nbsp; Class: __________ &nbsp; Date: __________
            </div>
            <div className="worksheet-instructions">
              Answer all {worksheet.length} questions. Circle the correct option.
            </div>

            <ol className="worksheet-questions">
              {worksheet.map((q, i) => (
                <li key={i} className="worksheet-q">
                  <div className="worksheet-q-text">
                    <strong>{i + 1}.</strong> {q.q}
                    <span className="worksheet-q-topic">{q.topicTitle}</span>
                  </div>
                  <ol className="worksheet-choices">
                    {q.choices.map((c, j) => (
                      <li key={j} className={showAnswers && j === q.correct ? "ws-correct" : ""}>
                        <span className="ws-letter">{LETTERS[j]})</span> {c}
                        {showAnswers && j === q.correct && <span className="ws-tick"> ✓</span>}
                      </li>
                    ))}
                  </ol>
                  {showAnswers && (
                    <div className="worksheet-why"><strong>Answer:</strong> {q.why}</div>
                  )}
                </li>
              ))}
            </ol>
            <div className="worksheet-footer">Generated by Tendo · {new Date().toLocaleDateString("en-GB")}</div>
          </div>
        </>
      )}
    </>
  );
}
