"use client";

import { useMemo, useState } from "react";
import { listBankTopics, sampleAcrossTopics, type BankQuestion, type SubjectId } from "@/lib/question-bank";

const LETTERS = ["A", "B", "C", "D"] as const;

type Difficulty = "all" | "easy" | "medium" | "hard";
type SubjectFilter = "all" | SubjectId;

interface SampledQ extends BankQuestion {
  topicId: string;
  topicTitle: string;
  subjectName: string;
}

const SUBJECT_ORDER = ["Mathematics", "English", "Integrated Science", "Social Studies"] as const;

export default function WorksheetGenerator() {
  const topics = useMemo(() => listBankTopics(), []);
  const subjectStats = useMemo(() => {
    const stats = new Map<string, { topics: number; questions: number }>();
    for (const topic of topics) {
      const existing = stats.get(topic.subjectName) ?? { topics: 0, questions: 0 };
      existing.topics += 1;
      existing.questions += topic.count;
      stats.set(topic.subjectName, existing);
    }
    return SUBJECT_ORDER.map((name) => ({ name, ...(stats.get(name) ?? { topics: 0, questions: 0 }) }));
  }, [topics]);

  const [subject, setSubject] = useState<SubjectFilter>("mathematics");
  const visibleTopics = useMemo(
    () => topics.filter((topic) => subject === "all" || topic.subjectId === subject),
    [topics, subject],
  );
  const [selected, setSelected] = useState<Set<string>>(() => new Set(topics.filter((t) => t.subjectId === "mathematics").map((t) => t.topicId)));
  const [count, setCount] = useState(15);
  const [difficulty, setDifficulty] = useState<Difficulty>("all");
  const [includeAnswerKey, setIncludeAnswerKey] = useState(true);
  const [worksheet, setWorksheet] = useState<SampledQ[] | null>(null);
  const [title, setTitle] = useState("P7 Mathematics worksheet");
  const [schoolName, setSchoolName] = useState("");
  const [className, setClassName] = useState("P.7");
  const [termName, setTermName] = useState("");
  const [durationMinutes, setDurationMinutes] = useState("");
  const [marksPerQuestion, setMarksPerQuestion] = useState(1);
  const [instruction, setInstruction] = useState("Circle the correct option for each question.");

  const liveSelectedQuestionPool = topics.filter((topic) => selected.has(topic.topicId)).reduce((sum, topic) => sum + topic.count, 0);
  const totalMarks = worksheet ? worksheet.length * marksPerQuestion : count * marksPerQuestion;

  function defaultTitleForSubject(nextSubject: SubjectFilter) {
    if (nextSubject === "mathematics") return "P7 Mathematics worksheet";
    if (nextSubject === "science") return "P7 Integrated Science worksheet";
    if (nextSubject === "social-studies") return "P7 Social Studies worksheet";
    if (nextSubject === "english") return "P7 English worksheet";
    return "P7 mixed-subject worksheet";
  }

  function changeSubject(nextSubject: SubjectFilter) {
    setSubject(nextSubject);
    const nextTopics = topics.filter((topic) => nextSubject === "all" || topic.subjectId === nextSubject);
    setSelected(new Set(nextTopics.map((topic) => topic.topicId)));
    setTitle(defaultTitleForSubject(nextSubject));
    setWorksheet(null);
  }

  function toggle(id: string) {
    setSelected((s) => {
      const next = new Set(s);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function selectAll() { setSelected(new Set(visibleTopics.map((t) => t.topicId))); }
  function selectNone() { setSelected(new Set()); }

  function generate() {
    const ids = Array.from(selected);
    if (ids.length === 0) {
      alert("Please select at least one topic.");
      return;
    }
    let pool = sampleAcrossTopics(ids, count * 3); // oversample so difficulty filter has room
    if (difficulty !== "all") {
      pool = pool.filter((q) => q.difficulty === difficulty);
    }
    if (pool.length === 0) {
      alert("No questions match those filters. Try widening the selection or difficulty.");
      return;
    }
    setWorksheet(pool.slice(0, count));
  }

  function copyAsText() {
    if (!worksheet) return;
    const lines: string[] = [];
    if (schoolName.trim()) lines.push(schoolName.trim().toUpperCase());
    lines.push(title.toUpperCase());
    lines.push("Generated by Tendo · " + new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }));
    lines.push(`Name: ____________________________   Class: ${className || "__________"}   Date: __________`);
    lines.push(`Term/Week: ${termName || "__________"}   Time: ${durationMinutes ? `${durationMinutes} minutes` : "__________"}   Marks: ${totalMarks}`);
    lines.push("");
    lines.push(`Instructions: Answer all ${worksheet.length} questions. ${instruction}`);
    lines.push("");
    worksheet.forEach((q, i) => {
      lines.push(`${i + 1}. (${q.subjectName} · ${q.topicTitle}) ${q.q}`);
      q.choices.forEach((c, j) => lines.push(`     ${LETTERS[j]}) ${c}`));
      lines.push("");
    });
    if (includeAnswerKey) {
      lines.push("ANSWER KEY");
      worksheet.forEach((q, i) => {
        lines.push(`${i + 1}. ${LETTERS[q.correct]} — ${q.why}`);
      });
    }
    const text = lines.join("\n");
    try {
      navigator.clipboard.writeText(text);
      alert("Worksheet copied. Paste into Word, WhatsApp, or your email.");
    } catch {
      const w = window.open();
      if (w) w.document.write(`<pre>${text.replace(/</g, "&lt;")}</pre>`);
    }
  }

  function printWorksheet() {
    window.print();
  }

  return (
    <>
      {!worksheet && (
        <div className="generator-form no-print">
          <div className="worksheet-stats" aria-label="Question-bank summary by subject">
            {subjectStats.map((item) => (
              <div className="worksheet-stat" key={item.name}>
                <strong>{item.questions}</strong>
                <span>{item.name}</span>
                <small>{item.topics} bank topics</small>
              </div>
            ))}
          </div>

          <h2>1. Worksheet details</h2>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Worksheet title"
            className="text-input"
          />
          <div className="generator-controls compact-controls">
            <input
              type="text"
              value={schoolName}
              onChange={(e) => setSchoolName(e.target.value)}
              placeholder="School name (optional)"
              className="text-input"
            />
            <input
              type="text"
              value={className}
              onChange={(e) => setClassName(e.target.value)}
              placeholder="Class e.g. P.7"
              className="text-input"
            />
            <input
              type="text"
              value={termName}
              onChange={(e) => setTermName(e.target.value)}
              placeholder="Term / week (optional)"
              className="text-input"
            />
          </div>

          <h2>2. Subject and topics</h2>
          <div className="subject-filter" role="group" aria-label="Worksheet subject">
            <button type="button" className={"subject-filter-btn" + (subject === "mathematics" ? " on" : "")} onClick={() => changeSubject("mathematics")}>Maths only</button>
            <button type="button" className={"subject-filter-btn" + (subject === "science" ? " on" : "")} onClick={() => changeSubject("science")}>Science only</button>
            <button type="button" className={"subject-filter-btn" + (subject === "social-studies" ? " on" : "")} onClick={() => changeSubject("social-studies")}>Social Studies only</button>
            <button type="button" className={"subject-filter-btn" + (subject === "english" ? " on" : "")} onClick={() => changeSubject("english")}>English only</button>
            <button type="button" className={"subject-filter-btn" + (subject === "all" ? " on" : "")} onClick={() => changeSubject("all")}>Mixed</button>
          </div>
          <div className="generator-toolbar">
            <button type="button" className="link-btn" onClick={selectAll}>Select all</button>
            <button type="button" className="link-btn" onClick={selectNone}>Select none</button>
            <span className="generator-count">{selected.size} selected · {visibleTopics.length} shown · {liveSelectedQuestionPool} questions available</span>
          </div>
          <div className="topic-chips">
            {visibleTopics.map((t) => {
              const on = selected.has(t.topicId);
              return (
                <button type="button" key={t.topicId} className={"topic-chip" + (on ? " on" : "")} onClick={() => toggle(t.topicId)}>
                  <span>{t.topicTitle}</span>
                  <span className="topic-chip-subject">{t.subjectName}</span>
                  <span className="topic-chip-count">{t.count}</span>
                </button>
              );
            })}
          </div>

          <h2>3. Length, marks and answer key</h2>
          <div className="quick-picks" aria-label="Quick worksheet lengths">
            {[10, 15, 20, 30, 40].map((n) => (
              <button type="button" key={n} className={"quick-pick" + (count === n ? " on" : "")} onClick={() => setCount(n)}>{n} questions</button>
            ))}
          </div>
          <div className="generator-controls">
            <label className="ctl">
              <span>Number of questions</span>
              <input type="number" min={1} max={50} value={count} onChange={(e) => setCount(Math.max(1, Math.min(50, Number(e.target.value) || 1)))} className="num-input" />
            </label>
            <label className="ctl">
              <span>Marks per question</span>
              <input type="number" min={1} max={10} value={marksPerQuestion} onChange={(e) => setMarksPerQuestion(Math.max(1, Math.min(10, Number(e.target.value) || 1)))} className="num-input" />
            </label>
            <label className="ctl">
              <span>Time allowed</span>
              <input type="number" min={1} max={180} value={durationMinutes} onChange={(e) => setDurationMinutes(e.target.value)} placeholder="minutes" className="num-input" />
            </label>
            <label className="ctl">
              <span>Difficulty</span>
              <select value={difficulty} onChange={(e) => setDifficulty(e.target.value as Difficulty)} className="num-input">
                <option value="all">Mixed</option>
                <option value="easy">Easy only</option>
                <option value="medium">Medium only</option>
                <option value="hard">Hard only</option>
              </select>
            </label>
            <label className="ctl">
              <span>Answer key</span>
              <select value={includeAnswerKey ? "yes" : "no"} onChange={(e) => setIncludeAnswerKey(e.target.value === "yes")} className="num-input">
                <option value="yes">Add separate answer key</option>
                <option value="no">Questions only</option>
              </select>
            </label>
          </div>

          <label className="ctl instruction-box">
            <span>Instruction line</span>
            <input type="text" value={instruction} onChange={(e) => setInstruction(e.target.value)} className="text-input" />
          </label>

          <div className="worksheet-preview-note">
            This worksheet will generate about <strong>{count}</strong> questions, worth <strong>{count * marksPerQuestion}</strong> marks, from <strong>{selected.size}</strong> selected topic{selected.size === 1 ? "" : "s"}.
          </div>

          <div style={{ marginTop: 24 }}>
            <button className="btn btn-primary btn-block" onClick={generate}>Generate worksheet</button>
          </div>
        </div>
      )}

      {worksheet && (
        <>
          <div className="generator-toolbar no-print" style={{ marginBottom: 24 }}>
            <button className="btn btn-secondary" onClick={() => setWorksheet(null)}>← Edit settings</button>
            <button className="btn btn-secondary" onClick={generate}>Shuffle again</button>
            <label className="toggle" style={{ marginLeft: "auto" }}>
              <input type="checkbox" checked={includeAnswerKey} onChange={(e) => setIncludeAnswerKey(e.target.checked)} />
              Include answer key
            </label>
            <button className="btn btn-secondary" onClick={copyAsText}>Copy as text</button>
            <button className="btn btn-primary" onClick={printWorksheet}>Print</button>
          </div>

          <div className="worksheet">
            {schoolName.trim() && <h2 className="worksheet-school">{schoolName.trim().toUpperCase()}</h2>}
            <h1 className="worksheet-title">{title}</h1>
            <div className="worksheet-meta-grid">
              <span>Name: __________________________</span>
              <span>Class: {className || "__________"}</span>
              <span>Date: __________</span>
              <span>Term/Week: {termName || "__________"}</span>
              <span>Time: {durationMinutes ? `${durationMinutes} minutes` : "__________"}</span>
              <span>Marks: {totalMarks}</span>
            </div>
            <div className="worksheet-instructions">Instructions: Answer all {worksheet.length} questions. {instruction}</div>

            <ol className="worksheet-questions">
              {worksheet.map((q, i) => (
                <li key={i} className="worksheet-q">
                  <div className="worksheet-q-text">
                    <strong>{i + 1}.</strong> {q.q}
                    <span className="worksheet-q-topic">{q.subjectName} · {q.topicTitle}</span>
                  </div>
                  <ol className="worksheet-choices">
                    {q.choices.map((c, j) => (
                      <li key={j}>
                        <span className="ws-letter">{LETTERS[j]})</span> {c}
                      </li>
                    ))}
                  </ol>
                </li>
              ))}
            </ol>

            {includeAnswerKey && (
              <section className="worksheet-answer-key">
                <h2>Answer key</h2>
                <ol>
                  {worksheet.map((q, i) => (
                    <li key={`answer-${i}`}>
                      <strong>{i + 1}. {LETTERS[q.correct]}</strong>
                      <span>{q.why}</span>
                    </li>
                  ))}
                </ol>
              </section>
            )}

            <div className="worksheet-footer">Generated by Tendo · {new Date().toLocaleDateString("en-GB")}</div>
          </div>
        </>
      )}
    </>
  );
}
